### ISSUE TITLE
Usuarios de prueba

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#100]
Se han creado tres usuarios de prueba para los 3 roles del sistema.
Se puede acceder a cada uno de ellos con los usuarios _ alumno, profesor, administrador_ para que los tutores del tribunal puedan realizar pruebas. La contraseña puede ser cualquiera.

**Comment by drg1006** [comment]
Podéis comprobar su funcionamiento.

¿Esto lo meto en la memoria?

@alvarag @annuskeras

**Comment by asermam** [comment]
Perfecto David.
Respecto a ponerlo en la memoria, puedes ponerlo donde hablas de cómo acceder a la aplicación, indicando que estos usuarios se han creado sólo para la defensa del TFG y que el despliegue para la demo se actualizará con la versión de producción en cuanto esta acabe.
