### ISSUE TITLE
Error al intentar ejecutar el proyecto.

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#16]
Tras importar el proyecto a Eclipse e intentar ejecutarlo siguiendo las instrucciones que se habían propuesto surge un error al lanzarlo en el puerto localhost:8080.

**Comment by drg1006** [comment]
El error es el siguiente: 
![image](https://user-images.githubusercontent.com/74197927/198106875-75ffd475-9a0c-45a3-bcf0-f2d107d40520.png)

**Comment by drg1006** [comment]
El proyecto se está ejecutando en vaadin 14.5.3, como se expresa en el pom.xml.
A pesar de ello, al importarlo a nuestro IDE la versión que pone en propiedades cambia a la 8.0.5.

Se ha intentado cambiar la versión del IDE de Eclipse a una más actualizada y el  fallo sigue existiendo.

También se ha intentado crear un proyecto de cero con una versión de vaadin 10+ y el proyecto de prueba que se crea se ejecuta correctamente, pero al intentar copiar los elementos que tenemos en nuestro repositorio principal, src junto al resto de carpetas, se cambia de igual manera a la versión 8.0.5 a pesar de que en el pom.xml sigue indicada expresamente la versión 14.5.3.

No he conseguido aún arreglar este error y por tanto no puedo ejecutar el código en local.
@alvarag @annuskeras

**Comment by alvarag** [comment]
Buenos días,

Ana lo ha instalado en dos equipos distintos (Win y Linux) y en ningún caso ha tenido el problema que reportas. Es cierto que le aparece una excepción en Java al ejecutar, pero eso ya es un paso posterior (entiendo) al que te ocurre a ti, ¿verdad?

Revisa bien si los pasos que sigues son los correctos porque como te digo a Ana no le da problemas.

Saludos,

**Comment by drg1006** [comment]
Se han añadido al proyecto de forma manual las carpetas org y lib-provided que se encotraban en [sistinf-0.5.war](https://github.com/dbo1001/Gestor-TFG-2021/releases) y que no encontrabamos en [sistinf-0.7.war](https://github.com/mjuez/Gestor-TFG-2021/releases).

Aún así, y tras ejecutar el proyecto en local, no se ha conseguido solucionar el error, que sigue siendo el mismo.

**Comment by drg1006** [comment]
También se ha instalado el repositorio de [Diana-Gestor-TFG-2021](https://github.com/dbo1001/Gestor-TFG-2021) y tras instalarlo y ejecutarlo, el .war que se genera no es el mismo que aparece en [sistinf-0.5.war](https://github.com/dbo1001/Gestor-TFG-2021/releases), ya que no se general las carpetas mencionadas (org y lib-provided). Por lo que puede ser un problema del entorno de eclipse al crear el .war.

@alvarag @annuskeras

**Comment by alvarag** [comment]
Si no somos capaces de desplegar el .war de Diana, el problema será de nuestro Tomcat. Podría ser la versión o algún fichero de configuración del Tomcat en cuestión.

Actualmente tenemos desplegado el war de Mario Juez en un:

Apache Tomcat/8.5.39 (Ubuntu) | 11.0.15+10-Ubuntu-0ubuntu0.18.04.1

**Comment by asermam** [comment]
@drg1006 puedes por favor confirmarnos que has intentado desplegar el .war de Diana? . No el generado desde el proyecto de Diana, sino el war cogido directamente del repo. En los últimos mensajes no queda claro si esa prueba que comentaba Álvar está incluída.

**Comment by drg1006** [comment]
He hecho la prueba ahora desplegando el .war de Diana en eclipse con la siguiente configuración:
![image](https://user-images.githubusercontent.com/74197927/199705188-d5a712d9-94b9-47c8-bc10-908c002134a3.png)

Pero no consigue ejecutarse de manera correcta:
![image](https://user-images.githubusercontent.com/74197927/199705962-1b3593cc-9e4f-43e8-9dbb-88691187dede.png)

Voy a desplegar ahora el .war de Mario de la misma forma.

**Comment by alvarag** [comment]
Buenos días David,

He estado invirtiendo bastante tiempo en el despliegue y te comento lo que he observado:
- En primer lugar, yo genero el .war con mvn en mi ordenador y soy capaz de desplegarlo en el Tomcat 8 donde está desplegada la versión de Mario (que es la de DIana con dos cambios menores).
- Pero si trato de ejecutarlo en mi máquina con "mvn spring-boot:run", me aparece el error de ayer.
- A mayores, Ana ha hecho una prueba de acceder al properties mediante ruta "global" y también le ha funcionado.

De todo esto lo que yo empiezo a pensar es que el problema lo tenemos en nuestro servidor local Tomcat o en Spring.

Te planteo la siguiente prueba y, por favor, nos confirmas qué te sale:
- Levanta el tomcat que tienes instalado en tu máquina y accede al gestor de aplicaciones.
![imagen](https://user-images.githubusercontent.com/9881614/199706208-aa5fb83c-e1da-4868-8e2e-db7b33603313.png)

- Abajo tienes la opción de desplegar un war, con eso luego miras a ver si te funciona o no.

Lo que quiero es hacer el despliegue fuera de Eclipse para descartar si el problema es de "Eclipse" o de "Tomcat"

Saludos,

PD: Información sobre el gestor de aplicaciones de tomcat [aquí](https://javiergarciaescobedo.es/despliegue-de-aplicaciones-web/86-servidores-de-aplicaciones/312-despligue-de-aplicaciones-web-en-tomcat).

**Comment by drg1006** [comment]
He conseguido ejecutar el .war de Mario sin problema en localhost:8080 y también he podido ejecutar el .war de Diana ya que lo había importado mal.
Sistin 0.7
![image](https://user-images.githubusercontent.com/74197927/199707638-df1c91ea-f989-4ec4-ba77-082a64e1f5b8.png)

Sistin 0.5
![image](https://user-images.githubusercontent.com/74197927/199707711-4920e451-6a2c-4e2d-bd0c-c18fe1fc2622.png)

**Comment by alvarag** [comment]
Buenas noticias, entonces ahora generas tu .war con ```mvn package -Pproduction``` y a ver si puedes ejecutarlo

**Comment by drg1006** [comment]
El problema entiendo que sucede entonces al generar el .war cuando intentamos ejecutar el proyecto en Eclipse.

Voy a generar ahora el .war con mvn package -Pproduction.

**Comment by drg1006** [comment]
Tras ejecutarlo desde la terminal con mvn package -Pproduction y mvn spring-boot:run me sigue saliendo el mismo error, entiendo que se está generando mal el .war.

**Comment by alvarag** [comment]
No, no quiero que ejecutes con spring-boot:run. Lo que quiero es que abras el Gestor de Tomcat y despliegues el war que has generado tras hacer el -Pproduction. Así descartaremos que el problema sea de Tomcat o de Spring(Eclipse)

**Comment by drg1006** [comment]
Tras realizar todos los pasos indicados [aquí](https://javiergarciaescobedo.es/despliegue-de-aplicaciones-web/86-servidores-de-aplicaciones/312-despligue-de-aplicaciones-web-en-tomcat) he llegado a este punto:
![image](https://user-images.githubusercontent.com/74197927/199740169-fe9e4881-1e5b-460a-bb7f-af024a322a73.png)

(El número de sesiones es 1)

Tras intentar correr el .war generado me lleva a la siguiente página de Vaadin :
![image](https://user-images.githubusercontent.com/74197927/199740473-bc2e0554-40f6-40b5-8f50-1aee04b88329.png)


Lo mismo me pasa al intentarlo con los .war ya mencionados que si que funcionan en localhost:8080 desde el servidor de tomcat de eclipse.

**Comment by asermam** [comment]
Hola David,
Creo que lo propone Alvar es precisamente aislar el despliegue de Eclipse. No entiendo bien a qué te refieres con "intentar correr el .war generado".

Para desplegar el war, debes:
1) Generarlo ejecutando mvn package -Pproduction ( indicado en pág 72 de Anexos). 
2) Desde el gestor de aplicaciones de Tomcat ( desde la UI que ves en tu primera captura), indicar la ruta al war que acabas de generar y darle a Desplegar.

**Comment by drg1006** [comment]
Eso es lo que he hecho si.

**Comment by asermam** [comment]
Ok. Entonces no estamos en el mismo punto, pues yo también consigo desplegar el war sin problema como Álvar, probando con el .war "nuestro".

**Comment by drg1006** [comment]
Yo no consigo aún desplegar ningún .war desde el gestor de aplicaciones de Tomcat, ya que me sale el error de vaadin mencionado anteriormente.

**Comment by alvarag** [comment]
Supongo que deberías acceder a la dirección: localhost:8080/sistinf-0.7 si es que no has cambiado el nombre. No sé si eso que muestras de Vaadin es la aplicación u otra cosa. Vamos, la idea es que deberías poder desplegar el war de Diana y Mario (al menos) y el tuyo debería funcionar también.

**Comment by drg1006** [comment]
Pero si accedo a localhost:8080/sistinf-0.7 ya no estoy desplegando el .war desde el gestor de aplicaciones.

Yo puedo ejecutar los .war de Mario y de Diana desde localhost:8080/sistinf-0.7 y localhost:8080/sistinf-0.5 respectivamente pero desde eclipse. 
No he conseguido ejecutarlos desde el gestor de aplicaciones de Tomcat ya que cuando le doy a 'desplegar' (tras cargar el .war) me lleva a la pestaña de Vaadin mencionada.

**Comment by alvarag** [comment]
Es que esa pestaña es como que no tuviese acceso tu PC a Internet, ¿no? Entiendo que lo que haces es seleccionar el war y pulsar en el botón "Desplegar".

Es bastante extraño que no te deje. Si pruebas a desplegar el de Diana o Mario desde el manager de Tomcat te da el mismo error?

**Comment by asermam** [comment]
Al seleccionar el war y pulsar "Desplegar", si todo va OK debería aparecerte en la lista de aplicaciones del app Manager de Tomcat. En tu captuta no lo veo. Si te fijas, en esta captura, puedes ver cómo aparece sistinf-07 en mi lista de aplicaciones (última línea):

![image](https://user-images.githubusercontent.com/3430472/199933992-7fe3c9f6-ea14-415c-9a33-edef9e844733.png)

**Comment by drg1006** [comment]
Buenos días. 

Cuando intento "Desplegar" el .war me lleva al error de Vaadin Application diciendome que estoy offline.

He reinstalado Vaadin en Eclipse y he reinstalado Tomcat con la siguiente configuración cuando se ejecuta :
![image](https://user-images.githubusercontent.com/74197927/199966733-5d4f8ad1-5fd8-4660-a107-696de0cb3738.png)

Me gustaría si vuestra configuración es diferente para saber donde puede estar el problema.

Procedo ahora a reinstalar la versión de Eclipse (aunque el problema debería estar fuera ya que se está ejecutando tomcat desde la terminal)

**Comment by alvarag** [comment]
Buenos días,

Yo donde lo estoy desplegando es "Apache Tomcat/8.5.39 (Ubuntu) | 11.0.15+10-Ubuntu-0ubuntu0.18.04.1".

Dado que el problema parece que está ocurriendo en Windows, como te comenté ayer yo haría la prueba de crear una máquina virtual Ubuntu, instalar tomcat (en caso de que no esté instalado) y tratar de desplegar el war de Mario o Diana. Si eso no funciona me preocuparía mucho, sino esta claro que el problema es por alguna configuración de Tomcat en Windows.

Saludos

**Comment by drg1006** [comment]
He instalado una máquina virtual Ubuntu 18.04 y he instalado tanto maven como tomcat de manera correcta siguiendo los tutoriales [maven](https://ubunlog.com/apache-maven-instalacion-ubuntu/) y [tomcat](https://www.digitalocean.com/community/tutorials/install-tomcat-9-ubuntu-1804-es).

Y se ejecuta bien el localhost:8080 llegando al gestor de aplicaciones de Tomcat como se puede observar:

![image](https://user-images.githubusercontent.com/74197927/199995623-1816db7b-cd28-4d97-ba34-02721bfb0c5d.png)

Tras descargar los .war de Diana y de Mario me sigue surgiendo el mismo error que tenía tras ejecutarlo en Windows en Chrome:
Google Chrome:
![image](https://user-images.githubusercontent.com/74197927/199995929-9b65aa57-0492-49aa-807b-771c2a92ac3c.png)

FireFox:
![image](https://user-images.githubusercontent.com/74197927/199996023-be6bdbd5-5a0f-49ca-9c5a-4bde4ca554cc.png)


Estoy empezando a pensar que puede ser un problema de red, que de alguna forma este capada, o por la IP del dispositivo, o dirección vpn.

**Comment by drg1006** [comment]
Si lo ejecuto en Windows en Google Chrome me sale el mismo error (que no lo había mencionado):
![image](https://user-images.githubusercontent.com/74197927/199996729-2c318ce0-dacf-4d08-be61-a7c14e888e40.png)

**Comment by drg1006** [comment]
He desconectado el cortafuegaos y el proxy está desactivado.
Fuera de eso no se dónde puede estar el problema ya que me da tanto en la máquina virtual de Ubuntu como en Windows.
@alvarag @annuskeras

**Comment by asermam** [comment]
Hola, me cuesta pensar que sea problemas de conexión. ¿Has intentado ver los logs de Tomcat, a ver si te dan alguna pista?

**Comment by drg1006** [comment]
Hola, he leído los logs y el error es el siguiente:
![image](https://user-images.githubusercontent.com/74197927/200652203-1b3d4b27-3565-46e2-81e6-40957ffb85b8.png)

He conseguido cambiarlo siguiendo las instrucciones de [aqui](https://github.com/annotationsatharvard/catcha/issues/26) y por fin he podido desplegar el proyecto de manera correcta:

![image](https://user-images.githubusercontent.com/74197927/200652654-61e44892-8e2b-4300-b9e6-8500c2885b79.png)

Como se puede ver:

![image](https://user-images.githubusercontent.com/74197927/200652679-6d99bac1-9a8d-4e47-8858-926e2c33c3eb.png)

**Comment by drg1006** [comment]
También se ha podido desplegar el .war que generamos nosotros tras ejecutar mvn package -Pproduction sobre el proyecto de Mario. 

Finalmente también se ha podido desplegar el proyecto desde eclipse y ejecutarlo desde "Run on Server" con Tomcat  cambiando el parámetro "Dynamic Web Module" de "Project Facets" en las propiedades del proyecto a la versión 3.1y el error de _InStream_ a la hora de acceder al _path_ ya no sale.

**Comment by alvarag** [comment]
¡Perfecto! Lo primero que debes hacer es documentar todo esto en el Manual del Programador ante sde que se te olvide. ¿Hoy quieres tener reunión por la tarde?

**Comment by drg1006** [comment]
Si, ¡perfecto!
