### ISSUE TITLE
Número total de alumnos

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#31]
En la pestaña de _proyectos activos_ se muestra una información estadística sobre los proyectos, tutores y alumnos que tenemos distribuidos en los .csv.

![image](https://user-images.githubusercontent.com/74197927/201486390-dc2b5594-47d3-4df5-a742-37d5d228395a.png)

Estos datos se sacan del archivo: BaseDeDatosTFGTFM.xls y podemos observar una incongruencia entre las pestañas _N2 Alumno_ y _N3 Historico_ ya que en la primera pestaña mencionada tenemos la información sobre los alumnos que están registrados para asignar posibles TFGs (un total de dos alumnos), mientras que en la segunda hoja mencionada tenemos hasta alumnos con un ID de 7, es decir, solo tenemos 2 alumnos para poder asignar un TFG pero en el ejemplo tenemos un total de 7 "nombres de alumnos" diferentes.

Adjuntos capturas:
![image](https://user-images.githubusercontent.com/74197927/201486611-e622fa0f-fc77-4f21-923c-d2689bdb6565.png)

![image](https://user-images.githubusercontent.com/74197927/201486615-5492e6d8-8472-4949-ba4c-bcb6ea9e0d86.png)

Por eso mismo la información de alumnos totales es de 2 en vez de 7.

@alvarag @annuskeras

**Comment by alvarag** [comment]
Los alumnos según se van asignando se van eliminando de la pestaña Alumnos y se incorpora su nombre en Activos. Por lo tanto los alumnos involucrados son los de la pestaña alumnos (sin asignar) y los asignados (en activos). No sé si era esa la consulta

**Comment by drg1006** [comment]
Entiendo si.
