### ISSUE TITLE
Creación prototipo (mock-up) pantalla de estadísticas del profesorado

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#42]
Se utilizará la herramienta [Pencil](https://pencil.evolus.vn/) para la creación de las vistas preliminares de las pantallas nuevas a introducir en esta versión.

**Comment by drg1006** [comment]
He hecho una versión en Pencil que se vería asi:
![image](https://user-images.githubusercontent.com/74197927/204090031-006d0401-98b3-407b-afe9-089a62ad6bf0.png)


No se si toda la información que se expone es interesante o si es viable de hacer, pero es la idea general.

También estaría el apartado de Información en la parte inferior como en todas las pantallas:
![image](https://user-images.githubusercontent.com/74197927/204087110-2e369d56-2f81-4493-b6e5-ca403e0e052d.png)

**Comment by drg1006** [comment]
También me gustaría preguntar en un futuro cómo vamos a relacionar los datos ficticios que tenemos de los tutores (con nombres Tutor1, Tutor2, etc) a los nuevos nombres que hemos sacado del webscraping.

Es muy posible que se añadan más detalles en un futuro en esta pantalla, más gráficas representando el número de proyectos realizados filtrando por departamento(o por área) a lo largo de los años.
@alvarag 
@annuskeras

**Comment by alvarag** [comment]
Lo que vamos a hacer es coger los datos de TFGs de este curso académico y así puedes contar con datos reales que te "casen" con los del webscrapping

**Comment by drg1006** [comment]
Perfecto, ¿qué os parece el mock-up presentado arriba? ¿Es necesaria más información, o es viable y útil todo lo expuesto?

**Comment by alvarag** [comment]
Yo creo que estaría bien que se puedan seleccionar varios elementos y que "pinte" varias cosas al mismo tiempo. Por ejemplo que puedas seleccionar dos departamentos y te haga las gráficas con ello, o dos áreas...

Es decir, yo pondría una pantalla de qué elementos quieres comparar:
- Departamento
- Área
- Profesor

Un selector de años.

Y con ello que te saque la/s gráficas.

No obstante le voy a dar una vuetla a ver qué mas se me ocurre

**Comment by drg1006** [comment]
Entiendo más o menos que queremos filtrar los datos de la siguiente manera:
![image](https://user-images.githubusercontent.com/74197927/204628038-6eb3dd8d-04e8-49af-be4b-281af934fc9e.png)

Pero la información que tengo que poner en las gráficas sería algo como: ¿TFGs asignados por año? (ya sea filtrando por profesor, departamento o area).

Ya que cualquier otra gráfica indicaría poner en el eje de coordenadas u ordenadas muchos parámetros, ya sea seleccionado un departamento e indicando los profesores que pertenecen a él, o indicarlo por área, no se si me explico.

**Comment by alvarag** [comment]
La idea es mostrar varias líneas en el gráfico:
- Una par el profesor
- Otra por el área
- Otra por departamento...

Dependerá de lo que seleccione el usuario.

**Comment by asermam** [comment]
Entiendo que más que un "filtro" es una selección de qué quieres dibujar y en qué rango de año, de manera que vas agregando líneas a la gráfica, pero lo que se dibuja siempre en número de TFGs asignados por año. 

Es decir, que el usuario puede seleccionar por ejemplo varias áreas y un rango de años, y debería salir la gráfica con una línea por área ( y su correspondiente leyenda). Luego podrías seleccionar un profesor y se agregría su gráfica para poder comparar los datos del profesor con los de su área... y así sucensivamente.
Si el usuario quiere hacer desaparecer líneas de la gráfica se deseleccionaría la opción correspondiente ( en el ejemplo anterior podríamos deseleccionar un área para que desaparezca el área que no corresponde al profesor) y al actualizar la gráfica desaparecería esa línea.

Si seguimos este enfoque de agregar-desagregar líneas seleccionando y deseleccionando, añadiría una opción a la selección de cada campo (profe, área, departamento) que sea seleccionar todos ( y por tanto deseleccionar todos). 
También, si no queremos aplicar los cambios en real time a medida que cambian las opciones de selección, un botón de "Actualizar" para que se apliquen cambios al terminar la selección.

Luego lo vemos

**Comment by alvarag** [comment]
Exacto, esa es la idea Ana

**Comment by drg1006** [comment]
Vale, entiendo si. 
El único problema que veo es como hacer la selección de profesores, ya que al ser 267, poner un _CheckBox_ (como podriamos poner para areas y departamentos) me parece poner mucha información en pantalla, y creo que un _ComboBox_ (desplegable), solo permite asignar una opción.

**Comment by asermam** [comment]
Yo haría la selección con búsqueda por texto que incluya sugerencias/autocompletado.
