### ISSUE TITLE
Creación prototipo (mock-up) pantalla de creación del informe

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#43]
Se utilizará como hemos mencionado anteriormente la herramienta [Pencil](https://pencil.evolus.vn/) para la crear esta nueva pantalla.

**Comment by drg1006** [comment]
¿En el informe qué información tenemos que exponer exactamente? ¿Los informes se realizan para un profesor en concreto, o podemos realizar informes por departamentos o por áreas? @alvarag @annuskeras

**Comment by alvarag** [comment]
El informe va a ser una hoja de cálculo en el que aparecerán la información de cada profesor del área correspondiente. Creo que se puede mostrar una pantalla con las áreas y que puedas elegir para qué área o áreas hacer el informe.

El resultado podría ser una hoja de cálculo con varias pestañas una por cada área y en cada pestaña:
- nombre del profesor
- TFG dirigidos
- TFG codirigidos
- Créditos

**Comment by drg1006** [comment]
La pantalla sería muy simple y con pocas opciones, he realizado el siguiente diseño: (el comentario entre paréntesis no saldría en la pantalla)
![image](https://user-images.githubusercontent.com/74197927/204165253-73756973-7df1-48a6-9fce-79a1396edbe1.png)

**Comment by alvarag** [comment]
Sí, aunque veo innecesario indicar el número de áreas: mejor que aparezcan todas las áreas y el usuario seleccione las que le interesen.

Aquí la aplicación deberá consultar de qué áreas son el profesorado que está dirigiendo TFGs en el curso actual y así mostrar esas seleccionadas por defecto, que sea el usuario el que pueda deseleccionar algunas.

**Comment by drg1006** [comment]
Entiendo entonces que la vista sería algo así:
![image](https://user-images.githubusercontent.com/74197927/204240520-6fce1c40-714d-46a6-af6f-e2945c2576ea.png)

Además que saldrían como marcadas las áreas que tienen TFGs asignados en el curso actual.

**Comment by alvarag** [comment]
Yo lo veo bien así.
