### ISSUE TITLE
Implementación pantalla Generar informes

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#44]
Se comenzará a programar la pantalla de generación de informes.

**Comment by drg1006** [comment]
Para mostrar bien las áreas, que tienen TFGs asignados este año que como hemos mencionado queramos que salgan activas por defecto, debemos tener esa base de datos de TFGs asignados este año a cada profesor, o por areas.
@alvarag @annuskeras

**Comment by drg1006** [comment]
Actualmente la vista de esta pantalla es la siguiente: 
![image](https://user-images.githubusercontent.com/74197927/204365203-47ba3aef-87f0-459f-ba91-3677b96db8e3.png)

Se seleccionan las áreas que se quiera, se le da un nombre al archivo y posteriormente se pincha en el botón _Crear Informe_


El resultado es el siguiente: (faltan por crear los métodos para sacar los profesores de cada área y posteriormente la información de cada uno) 
![image](https://user-images.githubusercontent.com/74197927/204365709-f702d069-69ae-4aa1-be23-7dfafe321d68.png)

Existe también un problema para nombrar las hojas del excel ya que tienen un tamaño máximo de caracteres y el nombre de muchas de las áreas lo supera.

@alvarag @annuskeras

**Comment by asermam** [comment]
Para el tema de los nombres demasiado largos podrías modificar el nombre que te llega por uno más corto aplicando cambios en algunas palabras como Ingeniería-->Ing.  , Infraestructura-->Infra., Inteligencia Atificial--> I.A. ...

**Comment by alvarag** [comment]
Sí, habrá que abreviar. En realidad las áreas suelen tener una abreviatura aceptada, por ejemplo Organización de Empresas es OE, Lenguajes y Sistemas Informáticos es LSI... Lo que no sé es si poner un diccionario o directamente usar abreviaturas como comenta Ana.

No obstante, de momento puedes cortar a 31 que es el límite y vemos si se entiende

**Comment by drg1006** [comment]
Actualmente el informe que se crea es el siguiente:
Seleccionando estos parámetros:
![image](https://user-images.githubusercontent.com/74197927/205506954-46189aa3-7319-478f-a78b-c103ab6c545b.png)

Se crean las dos pestañas con la siguiente información:
![image](https://user-images.githubusercontent.com/74197927/205506978-5403cb5b-0ce8-4aae-9349-95602a283a22.png)

y

![image](https://user-images.githubusercontent.com/74197927/205506990-932fc0c6-e195-444d-88c4-106406f7df33.png)


Sin embargo, se crea un _null pointer_ cuando realmente obtenemos un tutor que si tiene TFGs asignados:
![image](https://user-images.githubusercontent.com/74197927/205507052-ce3c2e19-efcd-4d6f-9f1f-cc1148af9a72.png)

Si que obtiene bien los TFGs de los tutores, pero la excepción salta al intentar entrar en el _Map_ donde tenemos la información, aún estoy intentando ver donde puede estar el problema ya que _dataSet_ donde guardamos los datos es igual en el ejemplo de tutores sin TFGs que en el que si obtienen los TFGs.

**Comment by drg1006** [comment]
El problemas venia dado por el nombre de la hoja, ya que al crear una hoja para el área _Lenguajes y sistemas informáticos_ no se creaba con el nombre completo y se acortaba, por lo que luego al buscar esa página por el nombre completo no la encontraba.

Se ha solucionado el problema y la vista del informe es la siguiente:

![image](https://user-images.githubusercontent.com/74197927/205508287-8fcd3d07-cf62-47c1-a7c9-e6a3cd9158ac.png)


Falta la opción de añadir el curso específico del que se quiere crear el informe y no se si se requiere añadir más información dentro el informe.

@alvarag @annuskeras

**Comment by drg1006** [comment]
El problemas venia dado por el nombre de la hoja, ya que al crear una hoja para el área _Lenguajes y sistemas informáticos_ no se creaba con el nombre completo y se acortaba, por lo que luego al buscar esa página por el nombre completo no la encontraba.

Se ha solucionado el problema y la vista del informe es la siguiente:

![image](https://user-images.githubusercontent.com/74197927/205508439-a1e9a186-c156-47b7-8c20-c39959f7e0a1.png)



Falta la opción de añadir el curso específico del que se quiere crear el informe y no se si se requiere añadir más información dentro el informe y también la opción de descarga al usuario.

@alvarag @annuskeras

**Comment by asermam** [comment]
Hola. Esto tiene buena pinta David!
Habría que pensar en darle un orden alfabético a los datos, idealmente por apellido.
Respecto a los cmapos del informe, te sabrá decir mejor Álvar.

Por otro lado, para evitar futuros problemas con los nombres de pestañas, opciones de selectores y demás, sería bueno implementar un diccionario como creo que ya comentamos al plantear la selección de gráficas de la pestaña de histórico.

**Comment by alvarag** [comment]
La idea sería que saquemos en el informe lo siguiente:
- Año/curso académico (porque será seleccionando un curso, aquí tener en cuenta un año académico como desde el 1 de octubre)
- Tutor
- TFG dirigidos
- TFG codirigidos
- Créditos.

Los créditos a asignar se calcularán según esta fórmula:
- Alumnado matriculado en el curso académico * 0,66
- Ese total hay que dividirlo para directores (60%) y para el tribunal (40%).

Por lo tanto, si hay 100 alumnos matriculados hay 66 ECTS para repartir:
- Cada miembro del Tribunal se lleva un 6,6%.
- Cada tutor se lleva un 60% si dirige solo y un 30% si codirige con otro/a profesor/a. Aquí es donde solo considerarás a miembros de la EPS, si no es de la EPS quien figure como codirección se considerará como dirección única.

Importante, ese 0.66 ECTS por cada dirección deberá poderse configurar en el fichero de configuración que tenía Diana.

Espero haya quedado claro @drg1006

**Comment by alvarag** [comment]
Un último apunte, para saber el número de alumnos/as que hay matriculados deberás acceder a UBUVirtual y preguntar cuántos alumnos hay matriculados en TFGs. Aquí comprueba si te da ese dato o no, que sino hay que hacerlo por otra vía.

**Comment by drg1006** [comment]
Estoy intentando ver cuantos alumnos hay matriculados en TFGs.
Para ello he visto que existen APIs como utiliza Diana para sacar la información de los usuarios en [APIS](https://docs.moodle.org/dev/Web_service_API_functions).

He visto que podemos utilizar tal vez la API para sacar la asignatura de "TRABAJOS FIN DE GRADO":
![image](https://user-images.githubusercontent.com/74197927/205708896-73fa4dfa-4ac2-4191-b264-e46ba139ce67.png)
Y posteriormente utilizar
![image](https://user-images.githubusercontent.com/74197927/205708219-9c459acc-f0b6-4eab-854e-be10761f90e6.png)

Todavía estoy entendiendo poco a poco como lo hace Diana, pero para ello lo primero que hay que hacer es ¿realizar un login interno desde eclipse al Moodle, y posteriormente utilizar esa API?

Es que estoy un poco perdido con los JsonObjects que utiliza y estoy entendiéndolo poco a poco. ¿No podría utilizar la API si no inicio sesión?

**Comment by drg1006** [comment]
Lo que se está intentando hacer es, una vez iniciada sesión con un usuario, obtener el id del curso del TFG que en este caso es 2204, y utilizar la API _core enrol get enrolled users_ buscando los usuarios con ese ID, se ha creado una clase de la misma forma que están creadas el resto de funciones _WS_, pero retorna el siguiente error:
![image](https://user-images.githubusercontent.com/74197927/205724822-605f9c7a-17b8-4448-be73-2b9c4198511c.png)

Estoy buscando la información en el [tracker de moodle](https://tracker.moodle.org/browse/MDL-31349?jql=text%20~%20core_enrol_get_enrolled_users)

**Comment by alvarag** [comment]
En la documentación de Moodle (https://docs.moodle.org/dev/Enrolment_API) veo que está la función :

```Java
function get_enrolled_users(context $context, $withcapability = '', $groupid = 0, $userfields = 'u.*', $orderby = '', $limitfrom = 0, $limitnum = 0)
```

No sé si te puede servir

**Comment by asermam** [comment]
Hola, 
Por lo que veo en la documentación de la API la llamada que intentas hacer sólo admite 1 argumento (courseid) y es de tipo int. Se me ocurre que le estés pasando o bien otro tipo, o más argumentos. Compueba con el debugger la llamada REST que estés haciendo.

**Comment by drg1006** [comment]
El código que tengo para intentar obtener la información de los usuarios es el siguiente (una vez realizado login y con el id del TFG hardcodeado):
```Java
JSONArray jsonArray2 = UtilMethods.getJSONArrayResponse(CONTROLLER.getWebService(), new CoreGetEnrolledUsers(2204));
```

La clase que utilizo es la siguiente:
```Java
public CoreGetEnrolledUsers(int id) {
		super(WSFunctionEnum.CORE_ENROL_GET_ENROLLED_USERS);
		setId(id);
	}


	/**
     * Id del curso
     * 
     * @param courseid
     */
    public void setId(int courseId) {
        parameters.put("course", courseId);

    }

```
La _WSFunction_ es
```Java
CORE_ENROL_GET_ENROLLED_USERS("core_enrol_get_enrolled_users",2.1)
```
Por eso mismo no entiendo muy bien porqué me indica que el parámetro no es válido.
Intentaré debuggearlo para ver como se realiza llamada pero el error salta al hacerla entonces no llega a obtener ningún valor.

**Comment by alvarag** [comment]
Lo que se me ocurre es que sea porque no tienes acceso... Para comprobarlo deberías: montarte un Moodle en local, cambiar tu código para acceder a dicha dirección (en vez de UBUVirtual) y como es tu propia distribución te puedes meter ahí con credenciales de profesor y comprobar si te deja acceder a los alumnos matriculados con dicho rol. Es un poco trabajoso, pero no sé sino cómo comprobar si el error es por permisos o porque no accedes bienen la llamada

**Comment by drg1006** [comment]
Estoy actualmente añadiendo la opción de seleccionar el curso académico y me ha surgido una duda sobre los créditos.

¿Cómo obtendríamos los alumnos matriculados en el TFG de los años anteriores?
Es decir, utilizando la función (que aún no he conseguido hacer que funcione) igual podemos obtener los usuarios matriculados en este curso, pero no podríamos obtener los de otros años y por tanto no podemos obtener los créditos. No se si me explico.

No se si es posible pero lo más fácil sería tener una hoja de datos en la que se ponga los alumnos que se han matriculado por año al TFG.

Otra forma que veo es coger los alumnos que vienen en la hoja _BaseDeDatosTFGTFM.xls_ directamente.

**Comment by drg1006** [comment]
La vista es la siguiente: 
![image](https://user-images.githubusercontent.com/74197927/207443935-4183edbd-4e9f-43e1-896c-c2417750e8dc.png)

Y el excel quedaría así:

![image](https://user-images.githubusercontent.com/74197927/207444074-9cee774d-8e42-4cda-a869-2a9159b4fc8e.png)

**Comment by alvarag** [comment]
Efectivamente, el informe solo podría ser para el curso académico en curso. Ya que para los anteriores no tenemos datos de alumnado matriculado.

Recuerda añadir una columna con los ECTS calculados a partir de la formulita que te pasé

**Comment by drg1006** [comment]
Elimino entonces la opción de escoger el curso académico y sigo investigando la forma de obtener los alumnos matriculados.

**Comment by drg1006** [comment]
Estoy asignando los créditos a los profesores (con el total de alumnos matriculados asignado a 100) y tengo alguna duda.

Los directores que mencionas que se llevan el 60% del total de créditos a asignar,¿ son los tutores? y después ¿habría que dividir ese total entre el número de TFGs asignados en ese curso no? para saber cuantos créditos hay que asignar por TFG, entiendo.

El otro 40% del total que va para el tribunal que mencionas se llevaría 6,6% por ser tribunal (ya que hay 6 miembros del tribunal) y ¿se le sumarían los créditos si fuese tutor de algún TFG?

**Comment by alvarag** [comment]
Sí, director y tutor lo uso de manera indiferente: así que el 60% se lo lleva el tutor/director (si hay dos de la UBU cada uno se lleva 30%, si son tutores externos no cuentan).

En el fichero de configuración aparecerá una clave de ECTS por TFG y estará por defecto a 0.66

Por lo tanto coges el número de alumnos y multiplicas por 0.66 => ese número es el total de ECTS a repartir. El 60% va para dividir entre tutores y el 40% para el tribunal.

Por lo tanto los miembros del tribunal se llevan: su parte por dirigir los TFGs de sus chic@s y luego aparte la parte proporcional de ese 40% que hemos hablado

**Comment by drg1006** [comment]
En futuros _issues_ se detallarán las mejoras realizadas a la pantalla.
