### ISSUE TITLE
Implementación pantalla Estadísticas del Profesorado

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#45]
Se comenzará a programar la nueva pantalla de estadísticas de los profesores.

**Comment by drg1006** [comment]
Actualmente la vista se encuentra así:
![image](https://user-images.githubusercontent.com/74197927/204903359-a44ede84-490d-491c-8ccb-d024881bc340.png)

Ya se actualizan bien los datos de los ficheros, y se han añadido las _checkbox_ de departamentos y profesores

**Comment by drg1006** [comment]
Se ha añadido parte de la información estadística y tambien se ha implementado mediante un _ComboBox_ un campo para meter el nombre de un profesor con autocompletado.
![image](https://user-images.githubusercontent.com/74197927/204922443-e906c041-a8dc-4485-b08b-2a20388556e8.png)

**Comment by drg1006** [comment]
A la hora de representar los datos en la gráfica, sacaremos los datos de _BaseDeDatosTFGTFM.xls_, ¿añado como una pestaña extra la de _N3 Historico_ nueva (llamandola _N3 HistoricoProfes_) o la sustituyo por la que había anteriormente? Ya que igual provoca algún conflicto a la hora de obtener datos en el apartado de métricas que estaba antes.

N3 Historico anterior:

![image](https://user-images.githubusercontent.com/74197927/204924590-4cba53de-6d99-4340-9c76-76b4399df6ae.png)

N3 Historico nuevo:

![image](https://user-images.githubusercontent.com/74197927/204924656-02f3cff5-8eca-47a6-82c9-4e1a8365190c.png)

También había pensado en sustituir todo el documento pero creo que es sobrecargar de información la versión local del proyecto que se está realizando.

@annuskeras 
@alvarag

**Comment by asermam** [comment]
Hola,
Por lo que veo ambas tablas son iguales, con las misma columnas, salvo que una tiene datos reales y la otra ficticios. Yo creo que es mejor unifircarlas en una sola para simplificar y no añadir ruido. 
Quizá haya algo que no esté viendo, ¿qué conflictos crees que podría provocar en el apartado de métricas? ¿Igual puedes hacer una prueba y ver qué pasa?

**Comment by alvarag** [comment]
Buenos días,

La versión que yo te he pasado es la que hay actualmente en "producción". Así que los datos deberían ser coherentes. Lo que hice fue quitar nombres y notas para evitar problemas de la LOPD.

Puedes coger unas pocas líneas de esta nueva versión para hacer pruebas o usar directamente todo el xls, como mejor veas.

Saludos

**Comment by drg1006** [comment]
He encontrado un conflicto a la hora de cargar la pestaña de históricos y es que si utilizo el archivo que me pasasteis y no lo modifico, si que se visualizan bien los datos:
![image](https://user-images.githubusercontent.com/74197927/205064064-b9f6a344-0f18-44ef-8177-7de99d5d2f15.png)

Sin embargo, cuando modifico el archivo (para introducir la pestaña de Profesores: N4_Profesores) todas las pantallas cargan bien excepto la de _Historic_, estoy todavia buscando el problema pero aún no he encontrado la solución:
![image](https://user-images.githubusercontent.com/74197927/205065133-3db30b77-afe0-44a4-929a-a19c59a0d84a.png)

No entiendo porqué al principio se ejecuta bien y tras modificar el archivo sale el error, estoy intentando buscar donde falla y las excepciones salta en los metodos _getRanking_ por un fallo de conexión mediante fillo:
![image](https://user-images.githubusercontent.com/74197927/205069288-28030e7f-1066-428a-aa46-3ba66ec7167b.png)

.

**Comment by alvarag** [comment]
Parece que el problema es una fecha " 11/30/13". Me imagino que si cuando yo te lo doy va bien y tras modificarlo tu "se rompe" puede ser por algún tema del locale. Pinta que las fecha se estén cambiando de AAA/MM/DD a otra configuración, o algo similar

Revisa bien todo eso

**Comment by drg1006** [comment]
No veo a simple vista que se modifique ningún campo al "modificarlo", la única diferencia que veo tras revisar el archivo es que los campos de asignación y presentación son tipo _Fecha_ en vez de tipo _Texto_ como en el primer archivo, pero al cambiarlo sigue dando fallo igualmente, y como se ejecuta bien si no se "modifica" no creo que el fallo se encuentre en el código.

**Comment by alvarag** [comment]
No, yo tampoco creo que el fallo se encuentre en el código sino en la hoja de cálculo. La que yo te paso funciona, pero al modificarla con tu Office no: por eso creo que el problema viene de algún campo/configuración de la hoja de cálculo

**Comment by drg1006** [comment]
He conseguido que se lean todas las pestañas bien, pero realizando unos cambios en el excel:
-Los campos de fechaAsignacion y fechaPresentacion se han cambiado a campos de tipo _texto_
-El campo de Nota ya no es un aletatorio.entre(5;10), si no un valor natural de tipo _general_

Esta es la forma en la que teníamos estructurado el anterior excel.

**Comment by asermam** [comment]
Genial David,
Comprueba que este cambio en los tipos no afecta a las funcionalidades que utilizan esos datos. Esto me recuerda que si no los tienes ya planteados, deberías comenzar a plantear tests para proteger el código...
Ánimo, que queda poco tiempo y hay que apretar. Es importante que este tipo de cosas a más bajo nivel las resuelvas con pruebas y observando bien el código que ahora mismo eres el que más sabe de él... Esperar a que respondamos creo que no es práctico y puede hacerte no llegar a tiempo a la entrega.

**Comment by drg1006** [comment]
Los TFGs que tienen fecha de asignación y presentación con una diferencia de dos años, ¿en que curso los pongo?
Ejemplo:
![image](https://user-images.githubusercontent.com/74197927/206198766-3a9cec50-11ab-4aea-92e4-809245522ea0.png)

Ejemplo:
Al buscar los TFGs de un curso indico fecha de inicio: 2013-10-01 y fecha fin 2014-10-01, pero hay TFGs que no entran en esos parámetros de búsqueda.

**Comment by alvarag** [comment]
Buena pregunta... yo creo que cuando se busca se está interesado en fecha de defensa: podemos coger la de presentacion

**Comment by drg1006** [comment]
Actualmente la gráfica para los parámetros 

- Area: Lenguaje y Sistemas Informáticos
- Departamento : Ingeniería Informática
- Profesor: Raúl Marticorena

Es la siguiente (siendo profesores la linea inferior):
![image](https://user-images.githubusercontent.com/74197927/206247489-c7c71f9f-4ad5-4746-97c6-725740dfd00b.png)

Es coherente pero en los campos de Area y Departamento no he podido comprobar aún si cuenta todos los TFGs bien.

Falta aún implementar la capacidad de meterle varios parámetros de cada uno, es decir varios areas o departamentos, entiendo que sería hacer un for en el apartado _Series_ del chart:
![image](https://user-images.githubusercontent.com/74197927/206247878-cf13b145-02a1-470c-8db8-32d40ca58dfd.png)

En el siguiente commit se ve el código implementado.

**Comment by alvarag** [comment]
Tiene buen aspecto, revisa si cuadra el número con lo que tenemos en BBDD.

**Comment by drg1006** [comment]
En futuros _issues_ se detallarán las mejoras realizadas a la pantalla.
