### ISSUE TITLE
Consulta SQL para obtener las áreas de los profesores con TFGs asignados

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#49]
Habíamos hablado que para la vista del _Historico de Profesores_ solo ibamos a mostrar las áreas de los profesores que hayan tenido algún TFG asignado.

Para ello lo que se plantea es realizar una consulta con un join entre las pestañas _N4 Profesores_ y _N3 Historico_ teniendo en común el nombre del profesor y sacar el Área de los profesores que se encuentren en ambas pestañas.

El problema que he encontrado es que en el histórico hay algunos nombres que están abreviados, véase : 
![image](https://user-images.githubusercontent.com/74197927/205346613-9712450f-6fe3-4024-86b8-00e1278193c6.png)
 o 
![image](https://user-images.githubusercontent.com/74197927/205346631-d33f4d89-d41d-4175-b79f-f672f3692e71.png)
 nombre que al sacar del webscraping obtenemos con más apellidos:
![image](https://user-images.githubusercontent.com/74197927/205346731-fa98386d-85d8-4292-b4af-b9b639506163.png)

Por lo que actualmente no se puede hacer una consulta real a no ser de que se modifiquen todos los nombres con abreviaturas del excel.

@alvarag @annuskeras

**Comment by drg1006** [comment]
Estoy sustituyendo los tutores que tienen abreviaturas y me he encontrado también con algún tutor que tiene TFG asignado pero no se encuentra en la EPS como:
![image](https://user-images.githubusercontent.com/74197927/205438936-69dde544-6cc0-47c6-866d-6e4ef49e68ad.png)

Sobre todo lo he encontrado en los que TFGs que tienen dos tutores, muchas veces el segundo no pertenece a la EPS o es el tutor empresarial, por lo que de esos tutores no podría sacar el Área.

**Comment by alvarag** [comment]
Sí, aquellos profesores que no aparezcan en la EPS no saldrán en el informe. Ten en cuenta que si el tutor no es de la UBU no tiene sentido asignarle créditos

Lo de las abreviaturas, efectivamente hay que resolverlo a mano en el histórico
