### ISSUE TITLE
Error al intentar añadir varias Series en el gráfico.

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#50]
Como se menciona en el Issue #45 se están intentando meter varias Series en el parametro _withSeries_ de nuestro _Chart_.

Cuando se meten de forma manual con el formato: 
```
withSeries(new Series("NAME", array), new Series("NAME2", array2))
```
Se muestran las dos series.

El formato que acepta este parametro es de tipo _Series [ ]_ por lo que se está intentando introducir de manera automática varias Series y no tener que _hardcodearlo_.

No he encontrado la manera ya que todos las opciones del _chart_ como _setSeries()_ y _updateSeries()_ sobreescriben la serie anterior.

Lo que se ha intentado es crear cada Serie que es escogida por el usuario y guardarla en un Array para luego introducirlo en el parametro _updateSeries_, pero el formato no es correcto, y no he encontrado la solución para añadir varias o cómo guardar todas las series y añadirlas a la vez.
@alvarag @annuskeras

**Comment by drg1006** [comment]
En internet he encontrado varias formas de hacerlo:
-Creando un array _Series[ ]_ para ir introduciendo las series y posteriormente meterlos en _withSeries()_
-Creando un ArrayList : List < Series > y añadir las series y posteriormente meterlos en _withSeries()_

Ayer intenté hacer ambos sin éxito pero esta tarde volveré a intentarlo.

**Comment by alvarag** [comment]
¿Y por qué no te permite usando el array de Series o el arrayList? Qué errores te aparecen?

**Comment by drg1006** [comment]
Finalmente se ha conseguido realizar mediante el array de series y el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/74197927/207411689-d64ca25c-7946-4a71-aba0-08592f684869.png)

Si se seleccionan nuevos valores se borran los anteriores y se actualizan en la misma página.
Faltaría darles un color aleatorio a cada serie para poder diferenciarlos de manera correcta y veo un problema a la hora de seleccionar los profesores.
Con este formato de selección solo podemos pasar un profesor cada vez que indiquemos que queremos actualizar nuestra gráfica, estoy viendo como tal vez crear botones que aparezcan cuando seleccionas a un profesor para poder añadir varios, y poder eliminarlos posteriormente.
