### ISSUE TITLE
Error 500 URL Investigadores

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#53]
Estaba realizando la documentación y probando el funcionamiento del código para ir haciendo pantallazos y al intentar actualizar la base de datos realizar el _webscraping_ me he encontrado con el siguiente problema:
![image](https://user-images.githubusercontent.com/74197927/207708980-1a55fc82-b483-4332-9bab-c90baf2d6e44.png)

Entiendo que será un error puntual, pero os lo comento por si es algo más.
@alvarag @annuskeras

**Comment by alvarag** [comment]
Acabo de enviarles un e-mail a ver qué sucede. Te mantendré informado.
Saludos

**Comment by alvarag** [comment]
Ya está solucionado ;)
