### ISSUE TITLE
Creación pantalla de ofertas de TFG por parte de los tutores

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#55]
En esta pantalla solo los profesores, es decir se tendrán que revisar las credenciales del usuario, podrán subir nuevos tfgs que se añadirán a nuestra base de datos en la pantalla de activos, indicando lo siguientes parámetros:

- Titulo TFG
- Descripción
- Tutor1 (por defecto el usuario loggeado)
- Tutor2
- Alumno (por defecto 'Aalumnos si asignar')
- Curso de Asignación (por defecto el actual)

También se añadirá una nueva columna que indique el estado del TFG (pendiende o aceptado por parte de un administrador).

**Comment by drg1006** [comment]
Actualmente la vista se ve así:
![image](https://user-images.githubusercontent.com/74197927/207969172-b03aa4a2-103a-47d3-987d-8395055b4fe9.png)

Se muestra el código añadido en el siguiente commit.

**Comment by alvarag** [comment]
Algunos cambios respecto a lo que hablamos:
- Recuerda que debe haber 3 tutores.
- Si no rellena nada debe aparecer "Aalumnos sin asignar", esa A adicional permite facilitar la búsqueda.
