### ISSUE TITLE
Error al obtener información sobre un fichero actualizado.

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#56]
En la pantalla para proponer un TFG me surge una duda cuando quiero introducir un TFG tras haber subido ya uno.
Para realizar la modificación cuento el número de líneas del fichero y escribo el nuevo TFG en la siguiente a la última con un titulo.
Lo que hago es buscar la ruta donde se cargan los datos que en nuestro caso es la siguiente y añadir una linea:
```
C:\Users\Legion\eclipse-workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\sistinf\WEB-INF\classes\data\BaseDeDatosTFGTFM.xls
```
Al principio lee 69 líneas porque son las iniciales:
![image](https://user-images.githubusercontent.com/74197927/208262999-a21f5187-1f8a-4028-9c08-23aaa18f86d3.png)

Tras introducir una el resultado es el siguiente:
![image](https://user-images.githubusercontent.com/74197927/208263046-be7c1913-d80e-435b-a679-76ab6a480da8.png)

Se introduce la fila de manera correcta. 
Pero si vuelvo a introducir otro TFG, me dice que el número de líneas son 69 y no 70 como serían tras actualizarlo.

El código empleado es el siguiente:
```
 String path = this.getClass().getClassLoader().getResource("").getPath();
        String serverPath = path.substring(0, path.length()-17);
        
        ExternalProperties config = ExternalProperties.getInstance("/config.properties", false);
        String dir = config.getSetting("dataIn");
        String completeDir = serverPath + dir + "/";
        String fileName = "BaseDeDatosTFGTFM.xls";
        File file = new File(completeDir + fileName);
        
        String absPath = file.getAbsolutePath();       
        System.out.println("absPath "+absPath);
        try {
            FileInputStream inputStream = new FileInputStream(new File(absPath));
            Workbook workbook = WorkbookFactory.create(inputStream);
            fachadaDatos = SistInfDataFactory.getInstanceData();
            //Coger las lineas del fichero a actualizar
            int rowid = fachadaDatos.getTotalNumber(TITULO, PROYECTO).intValue()+1;
           ....
}
```

He comprobado y el fichero del cual se saca la información en _fachadaDatos_ es el mismo, por eso no entiendo cual puede ser el problema.

Puede ser también que cada vez que actualice la base de datos tenga que meter a mano esa línea en el fichero de datos principal y volver a compilar como hablamos una vez, pero me parece raro.

@alvarag @annuskeras

**Comment by drg1006** [comment]
Se ha modificado la forma de obtener la última fila del fichero a : 
```
int rowid = hoja.getLastRowNum();
```

Pero el resultado sigue siendo el mismo.

**Comment by alvarag** [comment]
Buenos días, se me ocurre que haya que "actualizar" el objeto BBDD en memoria. Es decir, puede que esté guardando en caché los datos leídos de la hoja de cálculo y ya no vuelve a mirar el fichero físico. ¿Qué se hacía cuando se sube un nuevo fichero desde el botón de actualizar? Supongo que ahora el tratamiento debeŕia ser algo similar

**Comment by drg1006** [comment]
He visto que lo que hace es actualizar la instancia mediante:
```
 SistInfDataFactory.setInstanceData("XLS");
```
Este método lo que realiza es una actualización de la conexión con el fichero de base de datos.

Aún así esta vez no logra realizar de nuevo la conexión:
Este es el Logger que muestra
```
Creación de la conexión con el fichero XLS: /C:/Users/Legion/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TFG/WEB-INF/classes/data
```

No llega a encontrar el fichero de nuevo, estoy aún trazando el código pero no he encontrado el problema.

**Comment by drg1006** [comment]
Se ha conseguido escribir varios TFGs seguidos en nuestra base de datos, pero creo que aún no se ha conseguido actualizar la instancia de la base de datos que utiliza el servidor.

Como se ve aquí se consigue añadir varios TFGs:
![image](https://user-images.githubusercontent.com/74197927/208745430-4764e2e3-3f47-4cc2-b612-1b59b845ec36.png)

El problema viene cuando después de añadir un TFG intentas acceder a la última pestaña de _Aceptar TFGs_:
 
![image](https://user-images.githubusercontent.com/74197927/208745516-6f78711d-7ea6-4818-bd25-10addb49a507.png)

Se crea una excepción, entiendo que al intentar crear los datos del XLS, estoy viendo aún cuando puede ser el problema.

**Comment by drg1006** [comment]
Se ha solucionado el error anterior, ya carga bien la página de Aceptar Proyectos cuando añades alguno en la pantalla de Subir TFGs, y se añaden a la tabla de pendientes.
