### ISSUE TITLE
Autentificar usuario mediante Login

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#70]
En el proyecto anterior solo se realizaba el _Login_ cuando queriamos actualizar los archivos _.csv_ de la base de datos, y solo puede realizarlo los usuarios con permisos de _update_, por lo que la propia clase de Login tenia una redirección a la _View_ de actualizar los datos.

Actualmente necesitamos realizar esta validación en otras dos pantallas, por lo que no se puede utilizar ese sistema que tras _loggearse_ te redirige a la pestaña de actualizar. 

Existen varias opciones:

- Crear tres pestañas de _Login_ diferentes para redirigir posteriormente a la pestaña que deseemos (Repetir mucho código pero es lo más fácil de realizar, no es eficiente)
- Pedir al usuario que se _loggee_ cuando quiere acceder a cualquiera de las pantallas que necesita autorización y una vez _loggeado_ proporcionar tres botones que permitan al usuario navegar a las 3 pestañas. (No se repite código, es sencillo y no hay que cambiar la estructura, el usuario tiene que _loggearse_ cada vez que entra en cualquiera)
- Modificar el proceso de _login_ siguiendo las [instrucciones de vaadin](https://vaadin.com/docs/v14/flow/tutorial/login-and-authentication) restringiendo el acceso a ciertas pestañas sin haberse _loggeado_ antes. (Cambiar el proceso de _Login_ ya funcional, añadir varios archivos, aprender el desarrollo de este sistema, habría que estudiar la viabilidad, no necesitamos _loggearnos_ cada vez que intentamos acceder a una pestaña restingida, proceso más costoso).

@alvarag @annuskeras

**Comment by asermam** [comment]
Hola,
La tercera opción parece la más "elegante" y fácil de mantener. Intentaría apostar por esta (puedes crear una nueva rama para hacer las pruebas por si acaso) y si después de intentarlo ves que finalmente te va a consumir demasiado tiempo, acude a una opción más sencilla. Además no olvides comentar la tercera opción en la memoria tanto si la implementas como si no, por si hubiese que extender la funcionalidad en algún momento. 
Ánimo!

**Comment by drg1006** [comment]
De momento se ha implementado la opción 2, creando tres botones a las pantallas requeridas cuando el usuario se _loggee_ de forma exitosa, es decir, si pulsamos en los botones _Actualizar (del footer), Subir TFG o Aceptar TFG (de la barra de navegación)_, nos llevará a hacer el _loggin_ y una vez nos identifiquemos con los parámetros de _Update_ como previamente mencionamos, nos saldrán los botones para ir a esas pantallas.

![image](https://user-images.githubusercontent.com/74197927/210368757-c934a0d4-da95-4637-9013-2b3f96d418ad.png)

Los cambios se ven en el siguiente commit.

**Comment by drg1006** [comment]
En un entorno de prueba se está probando de momento la opción 3 mencionada, que todavía no se ha podido implementar correctamente, en el siguiente commit, en el apartado de pruebas se introducirán las clases que se han añadido para intentar implementar esta dinámica.

**Comment by alvarag** [comment]
Bien, lo interesante es tener una opción funcional (de momento). Cuando vayas a probar alternativas (la implementación de la opción 3, por ejemplo) lo interesante es crear una rama y hacer los cambios en esa rama. Así tienes toda esa funcionalidad (que puede salir mal) en una rama totalmente aparte.

Mañana revisaré la documentación, así que sube todo lo que tengas hasta ahora.

Último detalle, esta era la función que usabas para ver los roles de los usuarios, no? ```core_enrol_get_enrolled_users```

**Comment by drg1006** [comment]
Vale perfecto, sí era esa.

**Comment by drg1006** [comment]
He implementado otra forma de realizar el Login y autentificar el usuario:

- Ahora la primera pantalla que aparecerá será la de _Login_ y pedirá al usuario que se identique.
![image](https://user-images.githubusercontent.com/74197927/211781154-f4d66b11-c221-42dc-a7ef-e9882aebf879.png)

- De esta forma obtendremos si el usuario pertenece a la asignatura del TFG y sus permisos.
- Si pertenece a la asignatura de TFG pero no tiene permisos de update, se le redirigirá a la vista _InformationView_ y tendrá acceso a las siguientes pantallas:

![image](https://user-images.githubusercontent.com/74197927/211781246-8d1dbf60-487f-4fe2-b3f7-f1aa9ac3a1ad.png)

- Si el usuario tiene permisos de _update_ la pantalla que obtendrá será la siguiente:
![image](https://user-images.githubusercontent.com/74197927/211781447-87113e74-d531-4854-b277-fe6e9130aced.png)

- Además en el _Footer_ le aparecerá la opción de _Actualizar_ ficheros, mientras que al primer usuario no le aparecerá:

![image](https://user-images.githubusercontent.com/74197927/211781626-cf8a4373-df6d-46c5-b944-783d0987b778.png)


Falta por añadir una opción de Logout en el sistema pero creo que es una buena forma para controlar los accesos a las pantallas sin inciar sesión varias veces y validando el usuario una única vez. Aún así, el otro proceso de _Login_ mediante las instrucciones de Vaadin sigue en la rama TestBranch.

**Comment by drg1006** [comment]
Se han dividido los roles en tres:

- Administrador : usuario con permisos de update  true
- Profesor : usuarios sin permisos de update pero con permisos de reports true
- Alumno : usuarios sin ninguno de estos permisos

De esta forma se les ha podido restringir la vista de ciertas de las pantallas dependiendo del rol que tenga.
