### ISSUE TITLE
Gráfico de comparativa TFG/curso

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#72]
Existen un par de problemas en el gráfico de compartiva de TFGs asignados. El primero es que si seleccionas un profesor y lo eliminas, te aparece como con check pero no te lo dibuja:

![imagen](https://user-images.githubusercontent.com/9881614/210518653-38a1e5db-1abf-4d41-9c86-22774a1b8faa.png)

Es decir, una vez quitas el profesor seleccionado, no se quita el check ni se elimina del campo de texto.

Una pregunta aquí: se muestran tanto direcciones como codirecciones, ¿verdad?

Otro detalle, creo que sería mejorable esta pantalla, lo vemos la próxima semana

**Comment by drg1006** [comment]
No entiendo muy bien a qué te refieres, no se si estás empleando la última versión o la de Heroku (que aún no está actualizada).

En mi versión diría que lo hace correctamente.

Solo se muestras direcciones, no codirecciones en este caso.

**Comment by alvarag** [comment]
Claro, yo uso lo desplegado en Heroku: puede estar desactualizado

**Comment by drg1006** [comment]
Actualizo la versión de Heroku y pruebas otra vez.

**Comment by alvarag** [comment]
Sin prisa, no te preocupes

**Comment by drg1006** [comment]
Está actualizada ya la última versión (lo único que aún están puestas las pantallas de subir TFG y aceptar TFG sin pasar por le Login aunque esté implementado lo de los botones tras el login)
