### ISSUE TITLE
Pantalla introducir nuevo TFG

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#73]
En la pantalla de introducir nuevo TFG:
- En el tutor debería aparecer un desplegable con los tutores (como has hecho en la del gráfico). Pero podría el usuario seleccionar un tutor que no apareciese.
- El curso de asignación debería ser el actual por defecto
- Una vez das a aceptar no sabes si ha ido bien o no

**Comment by drg1006** [comment]
Los campos tutor1 y tutor2 se han implementad como desplegables con todos los tutores y se ha dado la posibilidad de introducir tutores que no aparezcan en la lista.

También se ha añadido un _warning_ cuando se intenta introducir un TFG en el que el tutor1 y tutor2 tienen el mismo valor:
![image](https://user-images.githubusercontent.com/74197927/210538833-f33149ee-da09-46d1-a996-339d1e2216fb.png)

A su vez se indica si un TFG se ha añadido correctamente mediante una notificación:
![image](https://user-images.githubusercontent.com/74197927/210538932-7c15a52e-a599-4d72-8e23-63b2cea9a589.png)


El curso de asignación ya se indica el actual por defecto.

**Comment by alvarag** [comment]
Perfecto, lo único una vez se haya añadido correctamente que se borren todos los campos para evitar meter dos veces el mismo.

En cuanto a las pestañas creo que sería bueno una reorganización en función de los roles:
- Ofertar TFG: solo aparecerá a los tutores
- Administración: sólo aparecerá al administrador (esto incluirá las opciones de ofertar, gestionar (aceptar/denegar), informes...).

Para esto no sé si se puede hacer como un submenú que aparezca arriba cuando pusas sobre uno de los botones.

**Comment by drg1006** [comment]
El problema es que no conseguimos obtener los roles que podía haber en Moodle, con la función: core_user_get_course_user_profiles 
No funcionaba.

**Comment by drg1006** [comment]
Una pregunta, en la nueva funcionalidad de editar un TFG, ya que ahora vamos a editar proyectos activos, ¿esta edición es para pasarlo a la pestaña de historicos?, es decir, para añadirles ya una nota, url, fechaPresentacion... Ó ¿también se va a usar para editar TFGs que van a seguir en la pestaña de activos?, es decir, para añadirles un alumno nuevo, o un tutor nuevo.

No se si me explico, ya que sería editar un TFG de dos formas diferentes y no se si se puede hacer en una misma pestaña o tendría que añadir dos botones para realizarlo, ya que en la primera opción tendría que eliminar el proyecto de la pestaña de activos y añadirle a la de históricos y en la segunda no.

Si no me he explicado me lo comentáis.
@alvarag @annuskeras

**Comment by drg1006** [comment]
Se ha añadido la forma de introducir el tutor3 igual que el 1 y el 2. También se avisa al usuario de que está introduciendo un tutor que no es de la EPS.
