### ISSUE TITLE
Pantalla aceptar TFG

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#74]
Sería interesante poder aceptar/rechazar el TFG (tal y como está ahora) pero que también se pueda editar. En plan, cuando seleccionas uno puedes editarlo, te llevaría a una pantalla como la de ofertar TFG y ahí puedes meter un alumno, cambiar cosas...

**Comment by alvarag** [comment]
Del mismo modo que en la pantalla anterior, no recarga y no sabes si lo ha hecho bien o no

**Comment by drg1006** [comment]
No había implementado al recarga automática ya que si un tutor decide de forma equivocada (a pesar de que tiene un pop-up con una confirmación) aceptar o denegar un TFG no tiene vuelta atrás, es decir de esta forma si acepta uno pero después quiere denegarlo porque se había equivocado puede hacerlo ya que aún no se ha actualizado la base de datos para "su vista".

Cuando dices que se puede editar el TFG te refieres a implementar otro botón que sea _Editar_ y crear una nueva pantalla en la que tengamos los datos del TFG que desea editar y poder modificarlos, ¿no?.
Debería ser fácil de hacer sí.

**Comment by alvarag** [comment]
Sí, la idea es que el administrador pueda editar el TFG aparte de aceptarlo/denegarlo. De hecho eso podría hacerlo en cualquier TFG en realidad (no solo en los nuevos) puesto que al final va a tener que introducirse la nota, fecha finalización, URL con repo...

Si quieres esta funcionalidad la comentamos en persona la próxima semana

**Comment by drg1006** [comment]
Puedo ir haciendo una pantalla parecida a la de aceptar/denegar TFGs, en la que aparezcan todos los TFGs activos, y que seleccionando uno de ellos te lleve a otra pantalla de edición de los parámetros.

**Comment by drg1006** [comment]
Una pregunta, en la nueva funcionalidad de editar un TFG, ya que ahora vamos a editar proyectos activos, ¿esta edición es para pasarlo a la pestaña de historicos?, es decir, para añadirles ya una nota, url, fechaPresentacion... Ó ¿también se va a usar para editar TFGs que van a seguir en la pestaña de activos?, es decir, para añadirles un alumno nuevo, o un tutor nuevo.

No se si me explico, ya que sería editar un TFG de dos formas diferentes y no se si se puede hacer en una misma pestaña o tendría que añadir dos botones para realizarlo, ya que en la primera opción tendría que eliminar el proyecto de la pestaña de activos y añadirle a la de históricos y en la segunda no.

Si no me he explicado me lo comentáis.
@alvarag @annuskeras

**Comment by alvarag** [comment]
El proceso sería, el administrador selecciona un TFG y pulsa en modificar:
- Cambia los campos que le interesen: URL, nota... etc.
- Tres botones: aceptar cambios y dejar abierto, aceptar cambios y mover a histórico y cancelar.

Porque la pantalla de modificar se puede usar para asignar un alumno a un TFG (y sigue estando activo) o para al final poner la nota y moverlo a histórico

**Comment by drg1006** [comment]
Se ha modificado la vista de Administrar TFGs y actualmente se muestran todos los TFGs activos:
![image](https://user-images.githubusercontent.com/74197927/212471786-8fa3897d-b6b3-4ba8-b6bb-89ba67be41ae.png)

Al darle a _Modificar_ cuando se seleccionan varios tfgs se le avisa con el siguiente _pop-up_:
![image](https://user-images.githubusercontent.com/74197927/212471814-6c1594f2-1387-4071-bb00-ca93e7e6c90a.png)

Solo podemos modificar uno, al indicarlo nos lleva a la siguiente pantalla, en la que se ponen por defecto todos los parámetros que había en la base de datos del TFG:
![image](https://user-images.githubusercontent.com/74197927/212472068-efa7a2bf-85a9-4f37-8838-846722b8f5dd.png)

**Comment by drg1006** [comment]
Quería preguntar qué parámetros son obligatorios para _Aceptar cambios y mover a histórico_, que ¿entiendo que serían todos?, excepto tutor2 y 3 y alumnos 2 y 3.
Por otra parte, la pestaña de históricos tiene un _Titulo Corto_ que hace referencia al _Titulo_ de la pestaña de activos, y además un _Titulo_ que normalmente es una referencia a github o al repositorio.
![image](https://user-images.githubusercontent.com/74197927/212472185-3933e24d-29ac-4340-8bbd-aca3e9610ff3.png)

También habría que indicar que los campos nota, fecha presentacion, fecha asignacion y repositorio no se pueden indicar si estamos intentando _Aceptar cambios y dejar abierto_.

**Comment by alvarag** [comment]
Sí, para mover a histórico tendría que tener todos los campos:
- Título: en realidad esto es una fórmula como verás en la hoja de cálculo. Si no me equivoco ya no se utiliza esta columna, antes sí se hacía para que fuera hipervínculo al repo.
- TítuloCorto: el título en verdad
- Descripción
- Tutores (1 obligado, más opcionales)
- Alumno1 obligado (el 2 opcional)
- Repositorio: opcional
- Fecha presentación, por defecto se rellenaría con la fecha actual del sistema pero la puede cambiar el usuario
- Fecha asignación: este campo lo rellena el tutor cuando oferta un TFG, pero lo puede modificar el admin cuadno lo acepta.
- Nota: obligatorio y del 0 al 10

**Comment by drg1006** [comment]
El problema con Fecha asignación es que al introducir un nuevo TFG no indicamos ese parametro, indicamos el curso de asignación, en muchos casos este valor es el curso y otros la fecha de subida del TFG, ya que no es no mismo, la fecha de subida que la fecha de asignación a un alumno:

![image](https://user-images.githubusercontent.com/74197927/212542904-32b2599e-00c6-49a1-855b-859125d1503a.png)

**Comment by drg1006** [comment]
Ya se ha implementado las opciones de modificación.
Se avisa al usuario de los parámetros que necesita introducir para realizar dicha modificación.
Mantener abierto:
![image](https://user-images.githubusercontent.com/74197927/212552394-a46a02a7-b215-4f29-868c-82e25d1e8c49.png)

Cerrar:
![image](https://user-images.githubusercontent.com/74197927/212552407-7cba1652-449c-4a3b-9af8-403bc384b373.png)

La opción de cancelar nos devuelve a la vista de todos los tfgs activos.

- Si actualizamos y dejamos abierto un tfg se modifica únicamente en la pestaña de activos.
- Si actualizamos la información y cerramos el TFG se procede a eliminar el tfg de la pestaña de activos y se introduce en la última fila de la pestaña de históricos.

Se avisa de ambas operaciones:
Abierto:
![image](https://user-images.githubusercontent.com/74197927/212552551-7d3f958e-06ca-4164-aca6-e41135639b25.png)

Cerrado:
![image](https://user-images.githubusercontent.com/74197927/212552581-121cb73e-c1fc-4626-8811-2d75bc5748da.png)


También se ha introducido un elemento de seguridad en el apartado de nota:
![image](https://user-images.githubusercontent.com/74197927/212552602-d9c74173-a6cb-4e46-a095-32d47f963095.png)

Y se han obtenido los días totales de duración del proyecto restando las fechas de asignación y presentación.

**Comment by alvarag** [comment]
El campo CursoAsignación en verdad es libre, si no hay nadie asignado se suele indicar el año en el que se oferta, ej: 2022-23 y cuando ya tiene alumno/a asignado/a se pone la fecha en la cual fue asignado (puede ser el día actual u otro anterior. Por lo tanto, ese campo se puede poder informar al ofertar TFG y al modificar

**Comment by drg1006** [comment]
En la pantalla de proponer TFG se indica el curso de asignación por defecto del curso actual, y posteriormente se puede modificar en la pestaña de _ModificarTFG_. Además de añadir también otro campo de fecha de asignación que se pone en la misma pestaña  de modificacion cuando se quiere cerrar el TFG, es decir, el campo de curso de asignación puede ser ambiguo y referirse a dos parametros.

**Comment by alvarag** [comment]
Sí, es totalmente ambiguo en verdad:
- Al inicio el TFG suele tener un curso
- Luego se asigna
- Luego se cierra

Pero en otras ocasiones, el propio tutor ya ha acordado un TFG para un alumno y en ese caso el campo contiene:
- Fecha en la que se asigna (y no el curso actual)
- Luego se cierra

No sé si queda claro

**Comment by drg1006** [comment]
Sí, se entiende.
Yo lo he implementado de tal forma que en la pantalla de propuesta de TFGs se ponga por defecto en el campo cursoAsignación el curso actual. Posteriormente cuando se quiera modificar está la opción del cursoAsignación (para la pestaña de activos como un campo de texto) y también el campo fechaAsignación (para la pestaña de histórico que si que necesita una fecha real):
![image](https://user-images.githubusercontent.com/74197927/212563386-0b305911-2f44-402f-82e6-92eb4330b3f8.png)

De esta forma si el profesor ha indicado ya una fecha de asignación en la pantalla de activos, aparecerá como el campo cursoAsignación en la de modificación y tendrá que volver a introducirlo para el campo fechaAsignación, no se si me explico.

**Comment by alvarag** [comment]
No te compliques, lo veo más sencillo un único campo que será curso/fecha asignación y que el usuario sea el que se encargue de meter ahí lo que corresponda

**Comment by drg1006** [comment]
A mi me parece más sencillo mi formato, que aunque el profesor tenga que introducir la fecha de asignación por segunda vez (en algunos casos) se hace más visual, ya que también he obtenido el número total de días con estos dos campos obtenidos mediante _DatePicker_
