### ISSUE TITLE
Ajustar el tamaño de los botones en la barra de navegación

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#77]
Como estuvimos comentando ayer, queríamos restringir vistas dependiendo del tipo de usuario que se _loggea_ en la plataforma. Una de las funcionalidades que dijimos de añadir era un _Desplegable_ en la barra de navegación, para usuarios profesores y administradores, en el apartado de Histórico, desplegando las dos opciones posibles, _De proyectos_ o _De profesores_.

He intentado realizarlo y me he topado con varias alternativas pero ninguna correcta:

- Realizarlo mediante el componente  [_MenuBar_](https://vaadin.com/docs/latest/components/menu-bar): el resultado sería el siguiente:
![image](https://user-images.githubusercontent.com/74197927/212069707-becbad35-d02d-4cc0-b7d1-2b9b19ec45e4.png)
           
Como podemos observar, existe una gran diferencia de tamaño, que he intentado modificar con los métodos _setHeight_ y _setWidth_ sin éxito. No he podido cambiar de tamaño de ninguna forma este elemento a pesar de intentarlo de todas las maneras posibles.

- Realizarlo mediante un _ComboBox_, un desplegable con dos opciones que también se utiliza como _input_ aunque en este caso no, el resultado es el siguiente:

![image](https://user-images.githubusercontent.com/74197927/212071848-f11f1bad-620c-4e61-9ec6-de7223d83192.png)

El tamaño tampoco se ajusta y no he conseguido al manera de cuadrarlo bien.

- Mediante un _Tab_, el problema es que no se pueden realizar desplegables dentro de un Tab, el resultado es el siguiente:

![image](https://user-images.githubusercontent.com/74197927/212072216-7c678f85-b282-415d-877a-7d7c56c1070c.png)

Yo creo que es mejor dejarlo finalmente en dos botones separados, indicando un titulo coherente, y se puede dejarla barra de navegación como estaba o con la nueva funcionalidad _Tab_ ya que _MenuBar_ crea los componentes en pequeño y no son modificables.
@alvarag @annuskeras

**Comment by alvarag** [comment]
Por no meter tanto botón en la barra superior, creo qeu lo mejor sería poner un par de botones en la propia página/vista de histórico y que por defecto esté activo el de TFG (al lado el de profesores, solo visible para profesores).

Sería desde mi punto de vista algo así:

```
+---------------------------------+
| Barra de menús                |
+---------------------------------+

Página/Vista de histórico:
+---------------+-----------------+
| TFG           | Profesores    |
+---------------+-----------------+

En función de lo que se seleccione se carga el TFG aquí o el de profesores
```

**Comment by drg1006** [comment]
Este sería el resultado final para un usuario _profesor_:
![image](https://user-images.githubusercontent.com/74197927/212131802-5c587ff8-4c50-4b80-b84d-a34ce3bb738e.png)

Se han añadido dos botones en la pestaña de historico (que por defecto muestra el historico de tfgs).
El usuario _alumno_ no tendrá estas dos opciones, que solo le aparecen al profesor y al administrador.
