### ISSUE TITLE
Actualización documentación

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#80]

**Comment by alvarag** [comment]
Comentarios sobre los documentos

[memoriaAAG.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10425434/memoriaAAG.pdf)
[anexosAAG.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10425435/anexosAAG.pdf)

**Comment by asermam** [comment]
[anexosASM.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10439933/anexosASM.pdf)
[memoriaASM.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10439934/memoriaASM.pdf)

Comentarios en documentación
