### ISSUE TITLE
Login opcional

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#82]
Estuve revisando los comentarios de la documentación de @alvarag y vi que comentaste que querías que el Login fuese opcional.

Puedo hacer que la vista general sea con los permisos de alumno y arriba a la derecha incluir un botón con _Log in_ que lleve a la pantalla de registro para posteriormente mostrar la barra de navegación correspondiente a cada rol. 
No se si es eso lo que quieres, puedo añadir también un botón de _Log out_, que lo había puesto como funcionalidad para añadir en futuras versiones, para que pueda deslogearse el usuario. ¿Es eso lo que comentas?

**Comment by alvarag** [comment]
Sí, esa era mi idea: el alumno no se hace login y si lo hace ve lo mismo que si no lo hace. El login solo para profesores: admin y no editor. Por lo tanto, un botón de logout es necesario.

**Comment by drg1006** [comment]
Se ha añadido el _Login_ opcional de la siguiente forma:
![image](https://user-images.githubusercontent.com/74197927/212976966-6acb8455-6db8-4c14-8262-085067b83602.png)

Cuando se inicia sesión se sustituye por el botón de _Log out_ :
![image](https://user-images.githubusercontent.com/74197927/212977078-513d2ada-e897-47b0-96d0-80b74979ebf8.png)

Estaba intentando poner este botón a la derecha del todo pero no he dado con la forma.

**Comment by alvarag** [comment]
Sí, la verdad que ahí queda un poco "descolgado", estaría mejor en la barra de botones

**Comment by drg1006** [comment]
¿Lo añado en la misma Barra que el resto pero al final? Puedo cambiarle el color o algo para que se diferencie del resto

**Comment by alvarag** [comment]
Es una opción, tal vez en vez de un nombre poner el símbolo de un usuario y un tooltip de inicio de sesión

**Comment by drg1006** [comment]
Así estaría bien:
![image](https://user-images.githubusercontent.com/74197927/212980162-6ae243eb-52aa-48f3-9eee-10ff1f0be9d8.png)
