### ISSUE TITLE
Corrección de la aplicación según lo visto en la reunión 18/01/2023

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#86]
Se procederá a realizar las correciones hechas por los tutores en la última tutoría.

**Comment by drg1006** [comment]
- Se ha eliminado el campo título del apartado administrar TFG, ya que no se utilizaba en los históricos.
- Se ha movido el botón _Metricas_ de la barra de navegación al final
- Se han corregido bugs.
- El curso de asignación en el apartado de nuevo TFG ahora es una fecha y no un curso como tal, es el que se recoge como fecha de Asignación en la pestaña de _Modificar TFG_ e indica por defecto el día en el que se está subiendo el TFG.
- El título _DATOS A MOSTRAR_ se ha puesto en minúsculas en la pestaña de histórico de profesorado.

**Comment by drg1006** [comment]
- Se han modificado los valores de la columna curso de Asignación, que tenían un valor tipo curso YYYY-YYYY, en la base de datos a un campo vacío o tipo texto con formato DD/MM/YYYY, para que no haya conflicto de tipos al recoger las fechas.
- Se ha modificado la visualización de la pestaña de Modificar TFGs.


Antes:
![image](https://user-images.githubusercontent.com/74197927/213499835-56f3b3a4-3396-452f-a6c6-1069ba17960e.png)

Después:
![image](https://user-images.githubusercontent.com/74197927/213507107-519dd8c5-089b-4a81-8ff5-0060138c5ada.png)

Los botones inferiores están desactivados hasta que no se seleccione una opción, si se pulsa en _SI_ se habilitará la siguiente vista:
![image](https://user-images.githubusercontent.com/74197927/213507770-c79a6bd5-adcd-4dcd-a9cb-3f4dc5a67640.png)

Se han permitido nuevos campos modificables y el botón de mover a histórico.

Si se pulsa en _No_ la vista será la siguiente:
![image](https://user-images.githubusercontent.com/74197927/213509336-69240913-3196-4202-8049-fee867be3a3f.png)


Se permite volver a pulsar en los botones _Sí y No_:

- Si pulsamos en No después de haber dicho que sí, volveremos a la situación previa. De esta forma impedimos que se puedan realizar las dos opciones a la vez. Otra forma de hacerlo es deshabilitando los botones _SI y No_ después de darle a uno, pero de esa forma tendriamos que cancelar y volver a recargar la página para deshacerlo si se ha pulsado de forma errónea.

¿Esta forma bien? @alvarag @annuskeras 

-

**Comment by drg1006** [comment]
- Se ha añadido la base de datos descargable en el _Footer_ para usuarios administradores:
![image](https://user-images.githubusercontent.com/74197927/213514257-309d6563-4105-487b-ba4a-2fc399a9cc32.png)

**Comment by alvarag** [comment]
Recuerda subir dicha versión a heroku

**Comment by drg1006** [comment]
Se ha actualizado a la última versión.

**Comment by asermam** [comment]
Comentarios a la nueva versión:
* Actualizar URL de la licencia, ahora mismo está la antigua https://github.com/drg1006/Gestor-TFG-2021/blob/master/LICENSE.md
* En las gráficas del histórico faltaría añadir información de qué se representa en cada una. Aunque está en la leyenda, debería aparecer, o bien en el título de la gráfica (ahora es el mismo para ambas: "Métricas agrupadas por curso") o bien en el eje vertical. 
* En la Sección de Proyectos activos, la ordenación por fecha no funciona bien
* En la sección de Informes, sigue quedando confusa la parte de selección de items. Como comentamos, "Seleccionar todas" debería de estar debajo de la cabecera "Áreas" (por cierto con tilde). Idealmente, el texto de ese encabezado Áreas debería de ser algo mayor ( o al menos no más pequeño) que el texto de las áreas en sí.
* El informe se crea con nombre por defecto "xls.xls", mejor utilizar algo más intuitivo tipo "Informe_TFGs.xls"
* En la pestaña de "Subir TFG" cambiaría el formato de fecha por el español, para que no de lugar a error. Es decir hoy 24 de Enero aparece como 1/24/2023, y debería de aparecer como 24/01/2023.
* Si subo un TFG, ¿no debería de aparecer en la lista de proyectos activos? Si lo subo a mi nombre no se guarda, si lo subo al de Álvar sí

**Comment by drg1006** [comment]
- Se ha actualizado la licencia.
- A mi la fecha que me aparece en "Subir TFG" me sale con el formato correcto: (utilizo el método getLocale(), también puedo _hardcodearlo_ a formato español)
![image](https://user-images.githubusercontent.com/74197927/214309275-abfce5f2-a743-4bbb-a5cf-d2ca1a01390b.png)

- Se ha cambiado de orden de la selección de Áreas en en el apartado de informes.
- A la hora de poner un nombre, puedo ponerle algún aviso al usuario, pero en teoría solo debería poner el nombre sin la extensión _.xls_

El resto de comentarios los sigo mirando.

**Comment by drg1006** [comment]
- También me deja introducir un TFG con tu nombre:

![image](https://user-images.githubusercontent.com/74197927/214311705-9c18d192-2e60-4d65-b93b-747cc70125a2.png)

**Comment by drg1006** [comment]
Se ha corregido el formato de las fechas que recogíamos como _string_ actualmente ya lo recogemos como un _LocalDate_, de esta forma se puede cambiar de formato y manejar de mejor forma.
Ya ordena bien en el apartado de proyectos históricos.
Se ha actualizado la versión en Heroku.

**Comment by asermam** [comment]
Hola,
- Sigue apareciéndome la fecha con otro formato. Mi navegador tiene el Locale Español. ¿Como accedes al Locale?
- El nombre del fichero del informe que se genera cuando se deja el campo vacío sigue siendo "xls.xls". Además he visto que se pueden generar informes sin haber definido el número de alumnos matriculados y sin haber seleccionado ningún área (en este segundo caso es un informe completamente vacío). ¿Quizá en lugar de eso deberíamos informar del error al usuario al pinchar en Generar Informe?
- La ordenación por fecha en "histórico" sigue sin funcionar bien
