### ISSUE TITLE
Manejo de Sesiones con Vaadin

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#88]
Se esta estudiando como trabajar el manejo de diferentes Sesiones en Vaadin, ya que actualmente se genera con variables globales.
Esta forma provoca conflictos entre las sesiones realizadas en distintos navegadores ya que guarda información de otros usuarios.

Lo que queremos es asignar variables a cada una de las sesiones que se creen.

**Comment by drg1006** [comment]
La forma en la que se está intentando realizar es mediante _VaadinSession_, ya que es la más recomendada y usada.

Siguiendo los pasos de [User Session](https://vaadin.com/docs/latest/advanced/application-lifecycle/#application.lifecycle.session), una sesión se debería crear cuando un usuario realiza una petición para abrir una URL, entiendo que al acceder a la pantalla de _información_, que en nuestro caso es la que esta por defecto, debería iniciarse una sesión.

El problema que tengo es que al intentar acceder a ella me dice que es _null_, ya que nosotros no iniciamos la aplicación mediante _VaadinServlet_ sino mediante _SpringBootServletInitializer_. Creo que este es el principal problema al intentar crear una sesión.

**Comment by drg1006** [comment]
También se está intentando realizar mediante _[ServletContext](https://docs.oracle.com/javaee/7/api/javax/servlet/ServletContext.html)_ como aparece [aquí](https://stackoverflow.com/questions/27933599/how-to-access-servletcontext-from-within-a-vaadin-7-app), pero creo que no sirve pare diferentes sesiones.

**Comment by drg1006** [comment]
Se ha probado utilizar _ServletContext_ pero no se modifica cuando se cambia de sesión, por lo que no se puede utilizar ya que hace referencia a atributos de toda la aplicación.
Se está investigando cómo realizarlo, sobretodo mediante _VaadinSession_, aunque seguimos obteniendo _null_.

Se han encontrado otras aplicaciones que realizan el manejo de sesiones de esta forma pero no he encontrado la solución:

- https://github.com/SELAB-AA/VaadinSessionManagement
- https://github.com/tonix-tuft/vaadin-session-uis-mapper
- Referencias de código: https://github.com/search?q=VaadinSession&type=code

**Comment by drg1006** [comment]
Creo que finalmente se ha dado con la solución, al menos en local si que puedo tener varias sesiones abiertas diferentes.

Se ha utilizado finalmente el método 
```
UI.getCurrent().getSession().setAttribute("---", "---");
UI.getCurrent().getSession().getAttribute("---");
```

Se ha subido a Heroku y me gustaría que comprobaseis si funciona. @alvarag @annuskeras

**Comment by drg1006** [comment]
He encontrado un problema a la hora de hacer _Log out_ que estoy intentando solucionar, ya que al pulsar este botón se redirige a la pestaña de _InformationView_, el problema es que si estás en esta pantalla no se recarga bien la aplicación. Estoy buscando la forma de obtener la clase en la que estamos al acceder una página.

**Comment by drg1006** [comment]
En teoría el problema ya está solucionado y la última versión está actualizada en Heroku.
Si podéis comprobar su funcionamiento, y funciona bien me decís.  @alvarag @annuskeras

**Comment by alvarag** [comment]
Yo creo que sí funciona bien, pero haré alguna prueba mañana con Ana.

Lo que no he visto que funcione bien es el tema del histórico, puesto que no me sale más que el de TFGs pese a ser admin yo.

**Comment by drg1006** [comment]
Se me había olvidado actualizar las pantallas de histórico, ya debería funcionar y está actualizado.
