### ISSUE TITLE
Creación de casos de prueba

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#90]
Se comenzarán a crear los casos de pruebamanuales para comprobar el correcto funcionamiento de las funcionalidades de la web, y ver si hay algún error.
Algunos de ellos se realizarán mediante excels con TFGs controlados y viendo si salen los datos que queremos obtener, hechos previamente a mano. Otros casos de prueba son los realizados al comprobar o avisar al usuario del correcto funcionamiento de la aplicación. 
Se intentará realizar un caso de prueba para cada funcionalidad añadida.

**Comment by drg1006** [comment]
En la gráfica de _tfgs asignados por curso_ en la pantalla histórico de profesores, ¿tengo que añadir tanto tfgs dirigidos como codirigidos? Es decir un proyecto podría sumar dos veces a un área si el tutor 1 y el 2 pertenecen a ese área, no se si me explico.

Al realizar los casos de prueba he caído en que solo contamos los tfgs dirigidos.
@alvarag

**Comment by drg1006** [comment]
A la hora de verificar el funcionamiento de la pantalla de _Subir TFG_ me he dado cuenta de que había un error al poner el título del TFG por defecto obteniendo el último tfg. Se ha solucionado cambiando la consulta _sql_ y ya funciona de manera correcta.

**Comment by alvarag** [comment]
Lo mejor para contabilizar codirecciones es contarlos como 1/2 proyecto. Un proyecto dirigido por un tutor vale 1 y uno con codirección cuenta 1/2. El tercer tutor nunca hay que tenerlo en cuenta para ninguna estadística porque suele ser alguien externo a la UBU.

**Comment by drg1006** [comment]
El problema de eso es que igual en la gráfica aparecerían entonces 2.5 tfgs asignados a un profesor o a un departamento, y podría generar dudas.

**Comment by alvarag** [comment]
Sí, soy consciente pero no es problema: los tutores saben que un TFG codirigido cuenta como 0.5 y no como 1

**Comment by drg1006** [comment]
- Ya se ha modificado la suma de los tfgs por curso, se añade 0,5 si es tutor1 y el tutor2 es de la EPS, también se añade solo 0,5 si es tutor 2 y se añade 1 si es tutor1 y no tiene tutor2 o no e de la eps.

Como se ve en el siguiente ejemplo, año 2021/2022:

![image](https://user-images.githubusercontent.com/74197927/215843264-acda7c4e-2a1b-434b-a8e5-4f4ea223aef1.png)

Excel:
![image](https://user-images.githubusercontent.com/74197927/215843367-4d68da39-2a31-4f94-922f-6b4c6c5392f0.png)

No está en ninguno como tutor2 ese curso, está como tutor1 en 3 pero uno compartido, así que suma 2.5 en total.
