### ISSUE TITLE
Errores a corregir

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#91]
Hago un issue para los diversos errores que he detectado probando la aplicación:

- Al denegar un TFG no se actualiza la tabla y parece que siguiese estando activo/pendiente. 
- Al crear un TFG, aparece un mensaje de "Estás seguro..." no consigo llegar a verlo porque desaparece y carga de nuevo. No sé a qué se debe pero conviene echar un vistazo a esa pantalla.
- No sé cómo poder cargar/descargar la base de datos, no lo localizo.
- En proyectos pendientes no hay uniformidad: hay mensaje modal al modificar (sin seleccionar TFG), pero en aceptar/denegar si no hay seleccionado proyectos aparece abajo a la izquierda. Unificar.
- Al cerrar sesión hay como dos cargas seguidas

**Comment by drg1006** [comment]
- Ya se ha añadido la base de datos.
- La doble carga en al cerrar sesión se realiza porque al cerrar sesión se redirige a la pantalla de Información, pero si estamos ya en esta pantalla no se recarga bien la página, he intentado obtener la página en la que se está actualmente para realizar un _if_ y no he encontrado la manera. Por lo que se redirige a la pantalla y después se recarga por si se estaba en la pantalla de información cuando se ha cerrado sesión.
- Se han añadido dos mensajes de validación cuando se intenta aceptar y denegar cuando no se selecciona ningún TFG.

El resto de _issues_ se están corrigiendo.

**Comment by drg1006** [comment]
- Ya se actualiza la tabla cuando aceptamos o denegamos un tfg.
- Ya se ha arreglado el problema de la notificación "Estas seguro" al añadir un TFG, que hace referencia al introducir un profesor que no es de la EPS

Ya está actualizado en Heroku.

**Comment by alvarag** [comment]
Nuevas pruebas realizadas con Ana en simultáneo:
- Login OK: solo vemos lo que debemos ver.
- Histórico: hay TFGs entregados en septiembre del 22 que deberían estar en el curso 22-23 y no aparecen en la gráfica dibujados
![imagen](https://user-images.githubusercontent.com/9881614/215712465-e40d0c94-2747-4266-85ec-5988c25eb40a.png)

- A Ana no le deja acceder a histórico y otras pantallas le da esta excepción
 ```
There was an exception while trying to navigate to 'Historic' with the exception message 'Error creating bean with name 'ubu.digit.ui.views.HistoricProjectsView': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [ubu.digit.ui.views.HistoricProjectsView]: Constructor threw exception; nested exception is java.lang.NullPointerException'
```

- Cuando se pide hacer webscraping llega un momento en el que deja de haber barrita azul arriba y el usuario pierde la noción de si se está cargando o qué pasa con la web... Igual hay que hacer esto de otro modo.
- Tras descargar el xls con la BBDD deja de funcionar toda proyectos activos... ```Constructor threw exception; nested exception is java.lang.ClassCastException: class java.lang.String cannot be cast to class java.time.LocalDate (java.lang.String and java.time.LocalDate are in module java.base of loader 'bootstrap')'```

**Comment by drg1006** [comment]
- Ya se ha corregido el tema de los permisos de Ana en Heroku.
- Cuando se realiza el webscraping sale una notificación en la parte inferior de la pantalla: 
![image](https://user-images.githubusercontent.com/74197927/215777068-f28f08c6-6a35-4c31-8595-f1263d44ef72.png)

- Estoy viendo el porqué se rompe o modifica la base de datos cuando lo descargamos, ya que no veo que se modifique, ni el descargado ni la base que se está utilizando.
- El histórico creo que ya se donde puede estar el problema ya que Diana recoge el último año de histórico según la fecha y no el curso, es decir la fecha 25/10/2022 recoge el año 2022. Estoy modificandolo.

**Comment by drg1006** [comment]
- La base de datos ya en principio se descargar bien y el programa sigue funcionando, al menos en local. Si puedes probarlo en Heroku, esta subido ya @alvarag

**Comment by drg1006** [comment]
- Todos los datos recogidos por Diana en la pantalla de histórico de proyectos están mal, estoy revisando el código pero teniendo en histórico estos proyectos con curso 2013/2014 (según la fecha de presentación y sin haber modificado el código):
![image](https://user-images.githubusercontent.com/74197927/215854867-1c4543d5-7cc9-4c75-94ef-0ca8786db8b9.png)

En la gráfica nos indica lo siguiente:

![image](https://user-images.githubusercontent.com/74197927/215854998-089193f8-0c20-4766-bd2a-da13234f939f.png)

Esto implicaría tener que rehacer toda esta pantalla.

**Comment by alvarag** [comment]
No entiendo el problema, en el histórico está la fecha de presentación con la que se puede saber en qué curso académico se presentó, ¿no? Si no recuerdo mal vimos bugs en esta pantalla de histórico al inicio del TFG, pensé que estaban resueltos cuando se hizo la puesta a punto de todos los bugs de la versión previa

**Comment by drg1006** [comment]
Sí, pero se como en la anterior versión diana solo cargaba 10 TFGs no tenía muchas casuísticas y el resultado le salía bien. Yo al cargar más no me di cuenta de que lo hacía mal.

**Comment by alvarag** [comment]
De acuerdo, habrá que corregirlo entonces: no es rehacer la pantalla sino corregir los cálculos que se hacen mal, ¿verdad?
