### ISSUE TITLE
Informe de dirección de TFGs

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#93]
Veo que el informe no está calculando bien los TFGs dirigidos y codirigidos. He descargado el informe de LSI (Lenguajes y Sistemas Informáticos) y la BBDD. Ejemplo Raúl, según el informe:
- 3 dirigidos
- 1 codirigidos

Según la BBDD este curso académico:
- GII 20.07 Representación gráfica de la matrícula: C.Pardo y él
- GII 21.08 Robótica-Denavit-Hartenberg: Lolo y él
- GII 21.43 Aplicación para invernadero automatizado IOT: Green in House: Antonio y él
- GII 22.09 Interfaz gráfica para la gestión de chatbots en la plataforma DialogFlow: él solo

El resto no contarían porque están sin alumnado asignado.

Si cojo a Lolo por ejemplo, según el informe no ha dirigido nada y no le da ECTS el estar en el tribunal... cuando tiene direcciones y codirecciones.

Importante: tal y como comenté al inicio hay que contar tanto los TFGs en curso (con alumn@ asignado) como los que se han presentado en este curso académico

**Comment by drg1006** [comment]
En teoría ya está solucionado y cuenta los tfgs de históricos.
