### ISSUE TITLE
Problemas en el webscraping

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#95]
Le he dicho que actualice los datos de profesorado por webscraping y no solo no lo ha hecho sino que en proyectos activos ya no me sale ningún TFG: curiosamente en histórico sí. Algo falla, hay que ver esta tarde bien una batería de pruebas

**Comment by drg1006** [comment]
Ya he solucionado el problema, estaba actualizando mal la instancia al recoger los datos, luego cuando realice más cambios actualizo la versión de Heroku.
