### ISSUE TITLE
Corrección pantalla de históricos

### ISSUE THREAD

**Issue by drg1006** [drg1006/Gestor-TFG-2022#96]
Como se comento en la reunión la pantalla de históricos de la versión pasada realizaba mal los cálculos sobre los datos del fichero.

Se van a corregir durante este sprint.

**Comment by drg1006** [comment]
De momento ya se ha corregido la primera parte de la pantalla, los resultados obtenidos son los siguientes, y tras realizar las pruebas a mano, son correctos:
![image](https://user-images.githubusercontent.com/74197927/216325304-952a13b5-0acd-4878-9d78-be2becc6b2d3.png)

Solucionando principalmente el problema que existía que era la asignación de un determinado proyecto a un curso.

**Comment by drg1006** [comment]
Se ha corregido también el segundo apartado:
![image](https://user-images.githubusercontent.com/74197927/216329338-8710fa70-1459-4537-a479-e1a19b4ff5d8.png)

No se exactamente si querías poner algo más en la pantalla @alvarag @annuskeras

**Comment by alvarag** [comment]
Sí, creo que con eso es suficiente
