### ISSUE TITLE
Acciones que despistan como usuario

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#98]
Tras usar un poco la aplicación te cuento cosas que despistan y deberían cambiarse para hacerla más "usable":
- Al seleccionar un TFG que no está pendiente, si pulsas en aceptar ó denegar, te pide confirmación y se queda ahí porque ya está aceptado y no puede hacer el cambio entiendo. Debería desaparecer el mensaje o decirte que ya está aceptado/cancelado. Pero en ningún caso quedarse ahí esperanod que des a "no"
- Cuando pulsas en modificar un TFG, tras realizar los cambios aparte de que te muestre el mensaje de "cambios realizados" debería irse a la pantalla principal. Sino es un poco raro.
- Revisar qué ocurre cuando se pasa a histórico un TFG desde la pantalla de administrar, puesto que lo he hecho y no he visto luego en histórico dicho TFG 
- Al crear/dar de alta un TFG no debería verse en Activos hasta que no se acepte por el administrador. Es decir, el ciclo es: alta -> revisión por parte del admin (acepta o deniega) -> pasa a la pantalla de activos -> el admin pasa a histórico -> se ve en la ventana de histórico

De hecho, recuerdo que una vez comentaste de poner un diagrama de flujo: puedes explicar el flujo de estados de un TFG en dicho apartado: dar de alta, pasa a pendiente, el admin lo acepta o no, pasa a activo o se borra, el alumno lo realiza, el administrador lo pasa a histórico...

**Comment by drg1006** [comment]
¿A qué te refieres con que en histórico no sale dicho TFG modificado?
Yo cuando modifico uno en local se añade correctamente a la pestaña de históricos si descargo la base de datos, y también se actualizan las estadísticas de las pestañas de histórico.

**Comment by alvarag** [comment]
Ahora sí lo ha hecho bien, no sé si lo habré mirado mal. Igual me he confundido

**Comment by drg1006** [comment]
Álvar una pregunta, ¿se puede modificar un tfg con estado pendiente?
Es decir, le digo al usuario que primero lo acepte para modificarlo, o si lo modifica y lo deja abierto cambio el estado a "aceptado"

**Comment by alvarag** [comment]
El proceso normal:
- Alta por parte de un tutor
- Lo acepta y/o deniega el admin: puede dejarlo aún sin alumno
- Luego el tutor le dice que un alumno esta interesado y ya modifica al alumno
- finalmente lo cierra y pone notas

**Comment by drg1006** [comment]
- Se han añadido avisos al usuario tanto al aceptar y denegar tfg si está ya aceptado de este tipo:
![image](https://user-images.githubusercontent.com/74197927/216387857-bbe8a69f-850e-4a6a-9514-9aaefbbf9faf.png)

- Los tfgs con estado "Pendiente" no aparecen ya en la pestaña de Activos.
- Se redirige a la pestaña de Administrar tfgs una vez se ha finalizado la operación de modificación.

**Comment by drg1006** [comment]
¿Entonces entiendo que no puedes modificar un TFG con estado "Pendiente"?

**Comment by alvarag** [comment]
El administrador o el usuario que lo ha creado? El usuario que lo creó ya no puede modificar nada. El administrador podría modificar cualquier cosa aunque estuviera en pendiente.

Por cierto, quita la restricción de que la URL sea obligatoria para cerrar un TFG

**Comment by drg1006** [comment]
Vale, pero mi pregunta es entonces:
Si un usuario administrador modifica un TFG con estado pendiente, (sin haberlo aceptado/denegado), cambia el estado del TFG a aceptado? Porque si hace una modificación entiendo que será porque lo quiere aceptar.

**Comment by alvarag** [comment]
Lo normal es que sí, que modifique y acepte, pero puedes dejarlo abierto y que pueda modificar y aceptar o denegar

**Comment by drg1006** [comment]
Entonces no modifico su estado, pero si le permito modificar un tfg con estado pendiente.

**Comment by alvarag** [comment]
El estado solo se modifica si acepta o deniega: si acepta se va a activo si deniega se borra de la BBDD.

**Comment by drg1006** [comment]
En teoría ya está todo actualizado en Heroku.
