### ISSUE TITLE
Líneas futuras

### ISSUE THREAD

**Issue by alvarag** [drg1006/Gestor-TFG-2022#99]
Ahora mismo el proceso de actualización de profesores/áreas/dptos es síncrono: esto implica que mientras está haciendo el webscraping la app deja de funcionar para todo el mundo.

Esto es algo muy mejorable, pero que habrá que dejar para líneas futuras, así que lo explicas que no se te olvide.

**Comment by drg1006** [comment]
Vale perfecto

**Comment by alvarag** [comment]
Comentarios en la memoria
[memoriaAAG.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10706473/memoriaAAG.pdf)

Y anexos:
[anexosAAG.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10706779/anexosAAG.pdf)

**Comment by drg1006** [comment]
Hola @alvarag, he corregido ya prácticamente todo de la memoria y los anexos que comentas, pero en el tema de asignar créditos a un tutor en el informe me has comentado esto: 
![image](https://user-images.githubusercontent.com/74197927/218091153-d5949002-486e-47ad-80f7-db97125d9bb7.png)


En su momento yo me fijé en esto que me indicaste en el issue #44 que es como está implementado.
![image](https://user-images.githubusercontent.com/74197927/218091284-996fe2fc-9440-4ece-b3b5-45096ed9b038.png)

De todas formas sería solo cambiar el 0.3 por un 0.5 para cada tutor en el código,

**Comment by alvarag** [comment]
Disculpa, igual no lo escribí bien porque ahora al leerlo veo que puede dar a malos entendidos. La idea es:

total_ECTS = nº alumnos * 0,66

a_repartir_para_tribunal = total_ECTS * 0,4 -> cada miembro del tribunal por lo tanto a_repartir_para_tribunal / número de miembros

a_repartir_tutores = total_ECTS * 0,6

a_repartir_tutores / número de TFGs -> esto es para cada TFG dirigido

Y si hay dos tutores dirigiendo => mitad para cada uno
Si hay un tutor todo para él.

No sé si así queda claro, sino te lo explico en videollamada

**Comment by drg1006** [comment]
Vale, entendido.

Anteriormente estaba así, entiendo que tengo que eliminar el *0.6 y el 0.3 debe ser un 0.5 ¿no?

```
// Recorremos todos los tfgs activos y con alumno asignado y buscamos si es
        // tutor1 o tutor2
        // y comprobamos si es codirigido por otro tutor de la EPS
        for (int n = 0; n < activos.dataActiveProjects.size(); n++) {
            // RECORREMOS SOLO LOS TFGS ASIGNADOS
            if (!activos.dataActiveProjects.get(n).getStudent1().equals("Aalumnos sin asignar")) {
                // SI ES EL TUTOR 1
                if (activos.dataActiveProjects.get(n).getTutor1().equals(profesor)) {
                    // SI EL TUTOR 2 ESTA O NO EN LA EPS
                    if (fachadaDatos.getProfesores().contains(activos.dataActiveProjects.get(n).getTutor2())) {
                        // Se reparten los creditos para este profesor en este tfg
                        nCreditosTutor += ectsPorTFG * 0.3;
                    } else {
                        // Se queda todo el porcentaje de los creditos
                        nCreditosTutor += ectsPorTFG * 0.6;
                    }
                    // SI ES EL TUTOR 2
                } else if (activos.dataActiveProjects.get(n).getTutor2().equals(profesor)) {
                    nCreditosTutor += ectsPorTFG * 0.3;
                }
            }
        }
```

Lo mismo para los proyectos históricos.

**Comment by alvarag** [comment]
No, yo como te lo veo lo tienes bien: 0.6 es para una dirección del TFG y si hay dos tutores cada uno se lleva 0.3

Lo que pasa es que tal y como esta explicado en el anexo yo entendía que estabas repartiendo más al tutor que al cotutor si hay cotutela.

Resumen:
- 1 tutor: nCreditosTutor += ectsPorTFG * 0.6;
- 2 tutor: nCreditosTutor += ectsPorTFG * 0.3; para cada tutor

Lo que pasa es que depende de cómo calcules ectsPorTFG, es el ectsPorTFGmatriculado o por dirección de TFG?

**Comment by drg1006** [comment]
El valor ectsPorTFG se calcula:

Multiplicando el número de alumnos matriculados en el TFG*0.66 , a ese valor se le multiplica por 0.6, que sería el porcentaje asignado para los tutores, y después lo divido entre el número de proyectos que están asignados este curso en total ( tanto en activos como ya en históricos, de este curso).

Entonces entiendo que si tendría que poner 0.5 a un tfg codirigido y dejarlo sin nada si es de un tutor solo.

**Comment by drg1006** [comment]
De forma paralela calculo el número total de créditos que tengo que asignarle al tribunal multiplicando el TFG*0.66 mencionado arriba por 0.4 y dividido entre 6 ya que son los miembros del tribunal.

**Comment by asermam** [comment]
Comentarios a la memoria
[memoriaASM.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10715878/memoriaASM.pdf)

**Comment by asermam** [comment]
Comentarios Anexos
[anexosASM.pdf](https://github.com/drg1006/Gestor-TFG-2022/files/10715933/anexosASM.pdf)

**Comment by drg1006** [comment]
Ya se han actualizado los pdfs de memoria y anexos sobre los comentarios que habíais puesto ambos.

Si @alvarag me puedes confirmar el cambio que te comenté al obtener los créditos por tfg de los informes para los tutores, daría todo por finalizado y subo la última versión a Heroku.

**Comment by alvarag** [comment]
> El valor ectsPorTFG se calcula:
> 
> Multiplicando el número de alumnos matriculados en el TFG*0.66 , a ese valor se le multiplica por 0.6, que sería el porcentaje asignado para los tutores, y después lo divido entre el número de proyectos que están asignados este curso en total ( tanto en activos como ya en históricos, de este curso).
> 
> Entonces entiendo que si tendría que poner 0.5 a un tfg codirigido y dejarlo sin nada si es de un tutor solo.

Sí, entiendo que es 0.5 para cada cotutor o el completo si es solo un tutor. Por favor, sube la versión a heroku final para comprobarlo

**Comment by drg1006** [comment]
Ya está actualizada la versión de heroku. @alvarag

**Comment by drg1006** [comment]
Ya se ha actualizado los anexos con los nuevos informes que se generan al modificar el código, y está todo actualizado.

**Comment by drg1006** [comment]
¿Puedo ir ya subiendo todos los documentos?
He visto que tengo que entregar lo siguiente:

- Un resumen de una página formato DIN A-4, en que se explique el contenido del TFG/TFM. ¿Entiendo que en formato físico?
- Una copia a papel de la memoria y anexos en la Secretaria de la EPS, junto con el siguiente [documento](https://www.ubu.es/sites/default/files/portal_page/files/2-entrega_proyecto_fin_de_grado_vena.pdf), también impreso.
- En la entrega de la asignatura de Trabajo de Fin de Grado una carpeta comprimida de todo el repositorio de GitHub.
- Y por último, tres copias digitales de todo el proyecto a entregar en Secretaría, pero no entiendo cómo, ¿un USB con tres carpetas iguales del proyecto?

@alvarag @annuskeras

**Comment by drg1006** [comment]
Además de entregar en ([Comunidad de Trabajo Fin de Grado en Ingeniería Informática](https://ubuvirtual.ubu.es/course/view.php?id=8574) una copia de la memoria y el anexo.
